// Pontos "fora da rota" para os 171 paises que faltavam (gerados por pesquisa
// multiagente, jun/2026). Mesma forma de atracoesForaDaRota.js: {nome, wiki, cidade, fora}.
// O `wiki` e titulo de artigo pt/en; resumoClient cai em en, e se falhar, o modal
// mostra o contexto do pais (nunca vazio). Foto via cadeia de fallback garantida.
// NAO regerar a mao -- reexecutar o workflow.

export const FORA_DA_ROTA_2 = {
  AD: [
    { nome: 'Vale de Madriu-Perafita-Claror', wiki: 'Madriu-Perafita-Claror Valley', cidade: 'Escaldes-Engordany', fora: true },
    { nome: 'Vilarejo de Os (Ordino)', wiki: 'Ordino', cidade: 'Ordino', fora: true },
    { nome: 'Igreja românica de Sant Joan de Caselles', wiki: 'Sant Joan de Caselles', cidade: 'Canillo', fora: true },
    { nome: 'Lago de Engolasters', wiki: 'Lake Engolasters', cidade: 'Escaldes-Engordany', fora: true },
    { nome: 'Casa de la Vall (parlamento histórico)', wiki: 'Casa de la Vall', cidade: 'Andorra la Vella', fora: true },
  ],
  AF: [
    { nome: 'Vale de Wakhan', wiki: 'Wakhan Corridor', cidade: 'Ishkashim', fora: true },
    { nome: 'Lagos de Band-e Amir', wiki: 'Band-e Amir National Park', cidade: 'Bamyan', fora: true },
    { nome: 'Minarete de Jam', wiki: 'Minaret of Jam', cidade: 'Shahrak', fora: true },
    { nome: 'Mazar-e-Sharif e Mesquita Azul', wiki: 'Shrine of Ali', cidade: 'Mazar-i-Sharif', fora: true },
    { nome: 'Cidadela de Herat', wiki: 'Citadel of Herat', cidade: 'Herat', fora: true },
  ],
  AG: [
    { nome: 'Devil\'s Bridge (ponte natural)', wiki: 'Devil\'s Bridge, Antigua', cidade: 'Willikies', fora: true },
    { nome: 'Ilha de Barbuda (Frigatebird Sanctuary)', wiki: 'Barbuda', cidade: 'Codrington', fora: true },
    { nome: 'Betty\'s Hope (engenho histórico)', wiki: 'Betty\'s Hope', cidade: 'Pares', fora: true },
    { nome: 'Shirley Heights (mirante e bateria)', wiki: 'Shirley Heights', cidade: 'English Harbour', fora: true },
    { nome: 'Half Moon Bay', wiki: 'Half Moon Bay, Antigua', cidade: 'Saint Philip Parish', fora: true },
  ],
  AL: [
    { nome: 'Parque Nacional de Theth', wiki: 'Theth National Park', cidade: 'Theth', fora: true },
    { nome: 'Vilarejo de Gjirokastër (cidade-pedra)', wiki: 'Gjirokastër', cidade: 'Gjirokastër', fora: true },
    { nome: 'Lago de Koman (travessia de ferry)', wiki: 'Lake Koman', cidade: 'Koman', fora: true },
    { nome: 'Sítio arqueológico de Apollonia', wiki: 'Apollonia (Illyria)', cidade: 'Fier', fora: true },
    { nome: 'Permet e fontes termais de Bënjë', wiki: 'Përmet', cidade: 'Përmet', fora: true },
  ],
  AM: [
    { nome: 'Mosteiro de Tatev', wiki: 'Tatev Monastery', cidade: 'Syunik', fora: true },
    { nome: 'Lago Sevan e Sevanavank', wiki: 'Sevanavank', cidade: 'Sevan', fora: true },
    { nome: 'Garganta de Debed (Sanahin)', wiki: 'Sanahin Monastery', cidade: 'Alaverdi', fora: true },
    { nome: 'Cidade de Gyumri', wiki: 'Gyumri', cidade: 'Gyumri', fora: true },
    { nome: 'Caverna de Areni-1', wiki: 'Areni-1 cave complex', cidade: 'Areni', fora: true },
  ],
  AO: [
    { nome: 'Quedas de Kalandula', wiki: 'Kalandula Falls', cidade: 'Malanje', fora: true },
    { nome: 'Parque Nacional da Kissama', wiki: 'Quiçama National Park', cidade: 'Bengo', fora: true },
    { nome: 'Pedras Negras de Pungo Andongo', wiki: 'Pungo Andongo', cidade: 'Malanje', fora: true },
    { nome: 'Deserto do Namibe (Iona)', wiki: 'Iona National Park', cidade: 'Namibe', fora: true },
    { nome: 'Serra da Leba', wiki: 'Serra da Leba', cidade: 'Lubango', fora: true },
  ],
  AT: [
    { nome: 'Hallstatt (vila alpina às margens do lago)', wiki: 'Hallstatt', cidade: 'Hallstatt', fora: true },
    { nome: 'Krimml Waterfalls', wiki: 'Krimml Waterfalls', cidade: 'Krimml', fora: true },
    { nome: 'Parque Nacional Hohe Tauern', wiki: 'Hohe Tauern National Park', cidade: 'Salzburg', fora: true },
    { nome: 'Eisriesenwelt (maior caverna de gelo do mundo)', wiki: 'Eisriesenwelt', cidade: 'Werfen', fora: true },
    { nome: 'Lago Wörthersee', wiki: 'Wörthersee', cidade: 'Klagenfurt', fora: true },
  ],
  AW: [
    { nome: 'Parque Nacional Arikok', wiki: 'Arikok National Park', cidade: 'Santa Cruz', fora: true },
    { nome: 'Vilarejo de San Nicolas', wiki: 'San Nicolaas', cidade: 'San Nicolas', fora: true },
    { nome: 'Piscina Natural Conchi', wiki: 'Conchi (Aruba)', cidade: 'Arikok', fora: true },
    { nome: 'Capela de Alto Vista', wiki: 'Alto Vista Chapel', cidade: 'Noord', fora: true },
    { nome: 'Ruínas da Mina de Ouro de Bushiribana', wiki: 'Bushiribana', cidade: 'Noord', fora: true },
  ],
  AZ: [
    { nome: 'Parque Nacional Gobustan (petróglifos)', wiki: 'Gobustan National Park', cidade: 'Qobustan', fora: true },
    { nome: 'Vila de Khinalug (povoado milenar nas montanhas)', wiki: 'Khinalug', cidade: 'Quba', fora: true },
    { nome: 'Yanar Dag (montanha em chamas)', wiki: 'Yanar Dag', cidade: 'Baku', fora: true },
    { nome: 'Sheki Khan\'s Palace', wiki: 'Palace of Shaki Khans', cidade: 'Shaki', fora: true },
    { nome: 'Lahij (vila artesã de cobre)', wiki: 'Lahij, Azerbaijan', cidade: 'Ismayilli', fora: true },
  ],
  BA: [
    { nome: 'Cidade velha de Počitelj', wiki: 'Počitelj', cidade: 'Čapljina', fora: true },
    { nome: 'Cataratas de Kravice', wiki: 'Kravice', cidade: 'Ljubuški', fora: true },
    { nome: 'Parque Nacional Sutjeska', wiki: 'Sutjeska National Park', cidade: 'Tjentište', fora: true },
    { nome: 'Vilarejo de Lukomir', wiki: 'Lukomir', cidade: 'Konjic', fora: true },
    { nome: 'Fortaleza de Travnik', wiki: 'Travnik Fortress', cidade: 'Travnik', fora: true },
  ],
  BB: [
    { nome: 'Cavernas de Harrison', wiki: 'Harrison\'s Cave', cidade: 'Allen View', fora: true },
    { nome: 'Vilarejo de Bathsheba', wiki: 'Bathsheba, Barbados', cidade: 'Bathsheba', fora: true },
    { nome: 'Animal Flower Cave', wiki: 'Animal Flower Cave', cidade: 'North Point', fora: true },
    { nome: 'Welchman Hall Gully', wiki: 'Welchman Hall Gully', cidade: 'Saint Thomas', fora: true },
    { nome: 'Reserva da Vida Selvagem de Barbados', wiki: 'Barbados Wildlife Reserve', cidade: 'Saint Peter', fora: true },
  ],
  BD: [
    { nome: 'Floresta de Sundarbans', wiki: 'Sundarbans', cidade: 'Khulna', fora: true },
    { nome: 'Ruínas budistas de Paharpur', wiki: 'Somapura Mahavihara', cidade: 'Naogaon', fora: true },
    { nome: 'Colinas de Bandarban', wiki: 'Bandarban District', cidade: 'Bandarban', fora: true },
    { nome: 'Praia de Kuakata', wiki: 'Kuakata', cidade: 'Patuakhali', fora: true },
    { nome: 'Mesquita Sixty Dome (Bagerhat)', wiki: 'Sixty Dome Mosque', cidade: 'Bagerhat', fora: true },
  ],
  BE: [
    { nome: 'Cidade medieval de Dinant', wiki: 'Dinant', cidade: 'Dinant', fora: true },
    { nome: 'Florestas das Ardenas', wiki: 'Ardennes', cidade: 'Bouillon', fora: true },
    { nome: 'Cidade histórica de Mechelen', wiki: 'Mechelen', cidade: 'Mechelen', fora: true },
    { nome: 'Beguinagem de Lier', wiki: 'Lier, Belgium', cidade: 'Lier', fora: true },
    { nome: 'Hautes Fagnes (reserva natural)', wiki: 'High Fens', cidade: 'Eupen', fora: true },
  ],
  BF: [
    { nome: 'Ruínas de Loropéni', wiki: 'Ruins of Loropéni', cidade: 'Loropéni', fora: true },
    { nome: 'Picos de Sindou', wiki: 'Sindou Peaks', cidade: 'Sindou', fora: true },
    { nome: 'Vilarejo de Tiébélé (casas pintadas Kassena)', wiki: 'Tiébélé', cidade: 'Tiébélé', fora: true },
    { nome: 'Reserva de Nazinga', wiki: 'Nazinga Game Ranch', cidade: 'Pô', fora: true },
    { nome: 'Cúpulas de Fabedougou', wiki: 'Fabedougou Domes', cidade: 'Banfora', fora: true },
  ],
  BG: [
    { nome: 'Mosteiro de Rozhen', wiki: 'Rozhen Monastery', cidade: 'Melnik', fora: true },
    { nome: 'Vila de Melnik', wiki: 'Melnik, Bulgaria', cidade: 'Melnik', fora: true },
    { nome: 'Parque Nacional Central Balkan', wiki: 'Central Balkan National Park', cidade: 'Kalofer', fora: true },
    { nome: 'Vila museu de Koprivshtitsa', wiki: 'Koprivshtitsa', cidade: 'Koprivshtitsa', fora: true },
    { nome: 'Pirâmides de Stob', wiki: 'Stob Pyramids', cidade: 'Stob', fora: true },
  ],
  BH: [
    { nome: 'Árvore da Vida no deserto', wiki: 'Tree of Life (Bahrain)', cidade: 'Jebel Dukhan', fora: true },
    { nome: 'Fortaleza Qal\'at al-Bahrain', wiki: 'Qal\'at al-Bahrain', cidade: 'Manama', fora: true },
    { nome: 'Necrópole de Aali (tumbas Dilmun)', wiki: 'Dilmun Burial Mounds', cidade: 'A\'ali', fora: true },
    { nome: 'Casa de Siyadi (Muharraq)', wiki: 'Siyadi House', cidade: 'Muharraq', fora: true },
    { nome: 'Mesquita Al Khamis', wiki: 'Al Khamis Mosque', cidade: 'Khamis', fora: true },
  ],
  BI: [
    { nome: 'Parque Nacional da Kibira', wiki: 'Kibira National Park', cidade: 'Bubanza', fora: true },
    { nome: 'Reserva Natural de Rusizi', wiki: 'Rusizi National Park', cidade: 'Bujumbura', fora: true },
    { nome: 'Quedas de Karera', wiki: 'Karera Falls', cidade: 'Rutana', fora: true },
    { nome: 'Parque Nacional de Ruvubu', wiki: 'Ruvubu National Park', cidade: 'Cankuzo', fora: true },
    { nome: 'Gishora Drum Sanctuary', wiki: 'Gishora', cidade: 'Gitega', fora: true },
  ],
  BJ: [
    { nome: 'Vilarejo lacustre de Ganvié', wiki: 'Ganvié', cidade: 'Ganvié', fora: true },
    { nome: 'Palácios Reais de Abomey', wiki: 'Royal Palaces of Abomey', cidade: 'Abomey', fora: true },
    { nome: 'Parque Nacional da Pendjari', wiki: 'Pendjari National Park', cidade: 'Tanguiéta', fora: true },
    { nome: 'Aldeias Tata Somba de Koutammakou', wiki: 'Koutammakou', cidade: 'Boukoumbé', fora: true },
    { nome: 'Mercado de fetiches de Akodessawa', wiki: 'Grand Popo', cidade: 'Grand-Popo', fora: true },
  ],
  BN: [
    { nome: 'Vila aquática Kampong Ayer', wiki: 'Kampong Ayer', cidade: 'Bandar Seri Begawan', fora: true },
    { nome: 'Parque Nacional Ulu Temburong', wiki: 'Ulu Temburong National Park', cidade: 'Temburong', fora: true },
    { nome: 'Tasek Merimbun', wiki: 'Tasek Merimbun', cidade: 'Tutong', fora: true },
    { nome: 'Cidade de Bangar', wiki: 'Bangar, Brunei', cidade: 'Bangar', fora: true },
    { nome: 'Cataratas Wasai Kandal', wiki: 'Wasai Kandal', cidade: 'Tutong', fora: true },
  ],
  BO: [
    { nome: 'Parque Nacional Madidi', wiki: 'Madidi National Park', cidade: 'Rurrenabaque', fora: true },
    { nome: 'Cordilheira de Sama (Reserva Biológica)', wiki: 'Sama Biological Reserve', cidade: 'Tarija', fora: true },
    { nome: 'Toro Toro (Parque Nacional)', wiki: 'Torotoro National Park', cidade: 'Torotoro', fora: true },
    { nome: 'Mercado das Bruxas de La Paz', wiki: 'El Mercado de las Brujas', cidade: 'La Paz', fora: true },
    { nome: 'Vilarejo de Coroico (Yungas)', wiki: 'Coroico', cidade: 'Coroico', fora: true },
  ],
  BR: [
    { nome: 'Lençóis Maranhenses', wiki: 'Parque Nacional dos Lençóis Maranhenses', cidade: 'Barreirinhas', fora: true },
    { nome: 'Chapada das Mesas', wiki: 'Parque Nacional da Chapada das Mesas', cidade: 'Carolina', fora: true },
    { nome: 'Jalapão', wiki: 'Parque Estadual do Jalapão', cidade: 'Mateiros', fora: true },
    { nome: 'Vale do Pati', wiki: 'Vale do Pati', cidade: 'Mucugê', fora: true },
    { nome: 'Serra da Capivara', wiki: 'Parque Nacional Serra da Capivara', cidade: 'São Raimundo Nonato', fora: true },
  ],
  BS: [
    { nome: 'Porcos nadadores de Exuma', wiki: 'Swimming pigs', cidade: 'Exuma', fora: true },
    { nome: 'Dean\'s Blue Hole', wiki: 'Dean\'s Blue Hole', cidade: 'Long Island', fora: true },
    { nome: 'Parque Nacional Exuma Cays Land and Sea', wiki: 'Exuma Cays Land and Sea Park', cidade: 'Exuma', fora: true },
    { nome: 'Lucayan National Park', wiki: 'Lucayan National Park', cidade: 'Grand Bahama', fora: true },
    { nome: 'Vila pesqueira de Spanish Wells', wiki: 'Spanish Wells', cidade: 'Eleuthera', fora: true },
  ],
  BT: [
    { nome: 'Vale de Phobjikha', wiki: 'Phobjikha Valley', cidade: 'Wangdue Phodrang', fora: true },
    { nome: 'Mosteiro Gangteng', wiki: 'Gangteng Monastery', cidade: 'Phobjikha', fora: true },
    { nome: 'Vale de Haa', wiki: 'Haa Valley', cidade: 'Haa', fora: true },
    { nome: 'Bumthang (vale sagrado)', wiki: 'Bumthang District', cidade: 'Jakar', fora: true },
    { nome: 'Trongsa Dzong', wiki: 'Trongsa Dzong', cidade: 'Trongsa', fora: true },
  ],
  BW: [
    { nome: 'Reserva de Caça do Kalahari Central', wiki: 'Central Kalahari Game Reserve', cidade: 'Ghanzi', fora: true },
    { nome: 'Colinas de Tsodilo', wiki: 'Tsodilo', cidade: 'Shakawe', fora: true },
    { nome: 'Parque Nacional Makgadikgadi Pans', wiki: 'Makgadikgadi Pans National Park', cidade: 'Gweta', fora: true },
    { nome: 'Reserva Natural de Khama Rhino', wiki: 'Khama Rhino Sanctuary', cidade: 'Serowe', fora: true },
    { nome: 'Vilarejo histórico de Serowe', wiki: 'Serowe', cidade: 'Serowe', fora: true },
  ],
  BY: [
    { nome: 'Floresta de Belovezhskaya Pushcha', wiki: 'Belovezhskaya Pushcha National Park', cidade: 'Kamyanyets', fora: true },
    { nome: 'Castelo de Mir', wiki: 'Mir Castle Complex', cidade: 'Mir', fora: true },
    { nome: 'Castelo de Nesvizh', wiki: 'Nesvizh Castle', cidade: 'Nesvizh', fora: true },
    { nome: 'Parque Nacional dos Lagos Braslav', wiki: 'Braslaw Lakes National Park', cidade: 'Braslaw', fora: true },
    { nome: 'Cidade histórica de Grodno', wiki: 'Grodno', cidade: 'Grodno', fora: true },
  ],
  BZ: [
    { nome: 'Caverna Actun Tunichil Muknal', wiki: 'Actun Tunichil Muknal', cidade: 'San Ignacio', fora: true },
    { nome: 'Sítio arqueológico de Lamanai', wiki: 'Lamanai', cidade: 'Indian Church', fora: true },
    { nome: 'Reserva de Vida Selvagem Cockscomb Basin', wiki: 'Cockscomb Basin Wildlife Sanctuary', cidade: 'Maya Centre', fora: true },
    { nome: 'Ruínas maias de Caracol', wiki: 'Caracol', cidade: 'Cayo', fora: true },
    { nome: 'Vilarejo costeiro de Hopkins', wiki: 'Hopkins, Belize', cidade: 'Hopkins', fora: true },
  ],
  CD: [
    { nome: 'Parque Nacional Garamba', wiki: 'Garamba National Park', cidade: 'Haut-Uele', fora: true },
    { nome: 'Parque Nacional Salonga', wiki: 'Salonga National Park', cidade: 'Mbandaka', fora: true },
    { nome: 'Parque Nacional Kahuzi-Biega', wiki: 'Kahuzi-Biega National Park', cidade: 'Bukavu', fora: true },
    { nome: 'Cataratas de Zongo', wiki: 'Zongo Falls', cidade: 'Kongo Central', fora: true },
    { nome: 'Lago Kivu (Goma)', wiki: 'Lake Kivu', cidade: 'Goma', fora: true },
  ],
  CF: [
    { nome: 'Parque Nacional Dzanga-Ndoki', wiki: 'Dzanga-Ndoki National Park', cidade: 'Bayanga', fora: true },
    { nome: 'Reserva Especial de Dzanga-Sangha', wiki: 'Dzanga-Sangha Special Reserve', cidade: 'Bayanga', fora: true },
    { nome: 'Parque Nacional Manovo-Gounda St. Floris', wiki: 'Manovo-Gounda St. Floris National Park', cidade: 'Birao', fora: true },
    { nome: 'Quedas de Boali', wiki: 'Boali Falls', cidade: 'Boali', fora: true },
    { nome: 'Cidade de Berbérati', wiki: 'Berbérati', cidade: 'Berbérati', fora: true },
  ],
  CG: [
    { nome: 'Parque Nacional Odzala-Kokoua', wiki: 'Odzala-Kokoua National Park', cidade: 'Cuvette-Ouest', fora: true },
    { nome: 'Cataratas de Loufoulakari', wiki: 'Loufoulakari Falls', cidade: 'Pool', fora: true },
    { nome: 'Reserva da Lésio-Louna', wiki: 'Lesio-Louna Reserve', cidade: 'Pool', fora: true },
    { nome: 'Diosso Gorges', wiki: 'Diosso Gorge', cidade: 'Pointe-Noire', fora: true },
    { nome: 'Parque Nacional Conkouati-Douli', wiki: 'Conkouati-Douli National Park', cidade: 'Kouilou', fora: true },
  ],
  CH: [
    { nome: 'Vale de Lavaux (vinhedos em terraços)', wiki: 'Lavaux', cidade: 'Lavaux', fora: true },
    { nome: 'Appenzell (vilarejo tradicional)', wiki: 'Appenzell', cidade: 'Appenzell', fora: true },
    { nome: 'Parque Nacional Suíço', wiki: 'Swiss National Park', cidade: 'Zernez', fora: true },
    { nome: 'Cataratas do Reno (Rheinfall)', wiki: 'Rhine Falls', cidade: 'Schaffhausen', fora: true },
    { nome: 'Aldeia de Soglio (Val Bregaglia)', wiki: 'Soglio, Switzerland', cidade: 'Soglio', fora: true },
  ],
  CI: [
    { nome: 'Parque Nacional de Taï', wiki: 'Taï National Park', cidade: 'Taï', fora: true },
    { nome: 'Cidade histórica de Grand-Bassam', wiki: 'Grand-Bassam', cidade: 'Grand-Bassam', fora: true },
    { nome: 'Montanhas de Man (Les Dents de Man)', wiki: 'Man, Ivory Coast', cidade: 'Man', fora: true },
    { nome: 'Parque Nacional de Comoé', wiki: 'Comoé National Park', cidade: 'Bouna', fora: true },
    { nome: 'Basílica de Yamoussoukro', wiki: 'Basilica of Our Lady of Peace', cidade: 'Yamoussoukro', fora: true },
  ],
  CK: [
    { nome: 'Ilha de Atiu (cavernas e kopeka)', wiki: 'Atiu', cidade: 'Atiu', fora: true },
    { nome: 'Ilha de Mangaia (a mais antiga do Pacífico)', wiki: 'Mangaia', cidade: 'Mangaia', fora: true },
    { nome: 'Lagoa de Aitutaki (One Foot Island)', wiki: 'Aitutaki', cidade: 'Aitutaki', fora: true },
    { nome: 'Ilha de Mauke (jardins de taro)', wiki: 'Mauke', cidade: 'Mauke', fora: true },
    { nome: 'Trilha Cross-Island de Rarotonga (Te Rua Manga)', wiki: 'Rarotonga', cidade: 'Rarotonga', fora: true },
  ],
  CM: [
    { nome: 'Parque Nacional de Waza', wiki: 'Waza National Park', cidade: 'Waza', fora: true },
    { nome: 'Aldeias Bamileke do Oeste (Bafoussam)', wiki: 'Bafoussam', cidade: 'Bafoussam', fora: true },
    { nome: 'Foumban (Palácio do Sultão Bamum)', wiki: 'Foumban', cidade: 'Foumban', fora: true },
    { nome: 'Cachoeiras de Ekom-Nkam', wiki: 'Ekom-Nkam Waterfalls', cidade: 'Nkongsamba', fora: true },
    { nome: 'Reserva do Dja', wiki: 'Dja Faunal Reserve', cidade: 'Sangmélima', fora: true },
  ],
  CN: [
    { nome: 'Vilarejo de Pingyao (cidade murada Ming)', wiki: 'Pingyao', cidade: 'Pingyao', fora: true },
    { nome: 'Aldeia de Wuyuan (vilarejos Huizhou)', wiki: 'Wuyuan County', cidade: 'Wuyuan', fora: true },
    { nome: 'Floresta de Pedra de Shilin', wiki: 'Stone Forest', cidade: 'Kunming', fora: true },
    { nome: 'Terraços de arroz de Yuanyang', wiki: 'Honghe Hani Rice Terraces', cidade: 'Yuanyang', fora: true },
    { nome: 'Vila antiga de Zhouzhuang', wiki: 'Zhouzhuang', cidade: 'Kunshan', fora: true },
  ],
  CV: [
    { nome: 'Vale do Paul (Santo Antão)', wiki: 'Santo Antão (Cabo Verde)', cidade: 'Santo Antão', fora: true },
    { nome: 'Vilarejo de Fontainhas', wiki: 'Fontainhas', cidade: 'Santo Antão', fora: true },
    { nome: 'Cidade Velha (Ribeira Grande)', wiki: 'Cidade Velha', cidade: 'Santiago', fora: true },
    { nome: 'Vulcão do Fogo e Chã das Caldeiras', wiki: 'Pico do Fogo', cidade: 'Ilha do Fogo', fora: true },
    { nome: 'Tarrafal e antigo Campo de Concentração', wiki: 'Tarrafal', cidade: 'Santiago', fora: true },
  ],
  CW: [
    { nome: 'Parque Nacional Shete Boka', wiki: 'Shete Boka National Park', cidade: 'Soto', fora: true },
    { nome: 'Bairro histórico de Pietermaai', wiki: 'Pietermaai', cidade: 'Willemstad', fora: true },
    { nome: 'Grutas de Hato', wiki: 'Hato Caves', cidade: 'Willemstad', fora: true },
    { nome: 'Praia de Playa Kenepa (Knip)', wiki: 'Playa Kenepa', cidade: 'Westpunt', fora: true },
    { nome: 'Parque Nacional Christoffel', wiki: 'Christoffelpark', cidade: 'Savonet', fora: true },
  ],
  CY: [
    { nome: 'Vilarejos de Troodos (Kakopetria)', wiki: 'Kakopetria', cidade: 'Nicósia', fora: true },
    { nome: 'Península de Akamas', wiki: 'Akamas Peninsula', cidade: 'Paphos', fora: true },
    { nome: 'Mosteiro de Kykkos', wiki: 'Kykkos Monastery', cidade: 'Troodos', fora: true },
    { nome: 'Sítio arqueológico de Choirokoitia', wiki: 'Khirokitia', cidade: 'Larnaca', fora: true },
    { nome: 'Aldeia de Lefkara (rendas)', wiki: 'Lefkara', cidade: 'Larnaca', fora: true },
  ],
  DJ: [
    { nome: 'Lago Abbe', wiki: 'Lake Abbe', cidade: 'Dikhil', fora: true },
    { nome: 'Lago Assal', wiki: 'Lake Assal (Djibouti)', cidade: 'Tadjourah', fora: true },
    { nome: 'Floresta do Day (Parque Nacional)', wiki: 'Day Forest National Park', cidade: 'Tadjourah', fora: true },
    { nome: 'Ilhas Moucha e Maskali', wiki: 'Moucha Island', cidade: 'Djibouti', fora: true },
    { nome: 'Khor Ambado', wiki: 'Khor Ambado', cidade: 'Djibouti', fora: true },
  ],
  DK: [
    { nome: 'Bairro de Christiania', wiki: 'Freetown Christiania', cidade: 'Copenhague', fora: true },
    { nome: 'Ilha de Bornholm', wiki: 'Bornholm', cidade: 'Rønne', fora: true },
    { nome: 'Museu Louisiana de Arte Moderna', wiki: 'Louisiana Museum of Modern Art', cidade: 'Humlebæk', fora: true },
    { nome: 'Penhascos de Møns Klint', wiki: 'Møns Klint', cidade: 'Borre', fora: true },
    { nome: 'Cidade velha de Ribe', wiki: 'Ribe', cidade: 'Ribe', fora: true },
  ],
  DM: [
    { nome: 'Trilha Boiling Lake', wiki: 'Boiling Lake', cidade: 'Roseau', fora: true },
    { nome: 'Indian River', wiki: 'Indian River (Dominica)', cidade: 'Portsmouth', fora: true },
    { nome: 'Vilarejo Kalinago Territory', wiki: 'Kalinago Territory', cidade: 'Salybia', fora: true },
    { nome: 'Cachoeiras Trafalgar', wiki: 'Trafalgar Falls', cidade: 'Roseau', fora: true },
    { nome: 'Soufrière Scotts Head Marine Reserve', wiki: 'Scotts Head, Dominica', cidade: 'Scotts Head', fora: true },
  ],
  DO: [
    { nome: 'Las Galeras (Península de Samaná)', wiki: 'Las Galeras', cidade: 'Samaná', fora: true },
    { nome: 'Constanza (vale alpino)', wiki: 'Constanza, Dominican Republic', cidade: 'Constanza', fora: true },
    { nome: 'Lago Enriquillo', wiki: 'Lake Enriquillo', cidade: 'Jimaní', fora: true },
    { nome: 'Parque Nacional Los Haitises', wiki: 'Los Haitises National Park', cidade: 'Sabana de la Mar', fora: true },
    { nome: 'Cachoeiras de Damajagua', wiki: '27 Charcos de Damajagua', cidade: 'Puerto Plata', fora: true },
  ],
  DZ: [
    { nome: 'Vale do M\'zab (Ghardaïa)', wiki: 'M\'zab', cidade: 'Ghardaïa', fora: true },
    { nome: 'Tassili n\'Ajjer', wiki: 'Tassili n\'Ajjer', cidade: 'Djanet', fora: true },
    { nome: 'Ruínas romanas de Timgad', wiki: 'Timgad', cidade: 'Batna', fora: true },
    { nome: 'Cidade de Constantine', wiki: 'Constantine, Algeria', cidade: 'Constantine', fora: true },
    { nome: 'Tipaza (ruínas fenício-romanas)', wiki: 'Tipasa', cidade: 'Tipaza', fora: true },
  ],
  EC: [
    { nome: 'Mercado de Otavalo', wiki: 'Otavalo', cidade: 'Otavalo', fora: true },
    { nome: 'Vulcão Cotopaxi', wiki: 'Cotopaxi', cidade: 'Latacunga', fora: true },
    { nome: 'Banhos de Água Santa', wiki: 'Baños, Tungurahua', cidade: 'Baños', fora: true },
    { nome: 'Lagoa Quilotoa', wiki: 'Quilotoa', cidade: 'Pujilí', fora: true },
    { nome: 'Reserva Mindo-Nambillo', wiki: 'Mindo, Ecuador', cidade: 'Mindo', fora: true },
  ],
  EE: [
    { nome: 'Ilha de Saaremaa (moinhos e cratera)', wiki: 'Saaremaa', cidade: 'Kuressaare', fora: true },
    { nome: 'Parque Nacional de Lahemaa', wiki: 'Lahemaa National Park', cidade: 'Palmse', fora: true },
    { nome: 'Vilarejo de pescadores de Käsmu', wiki: 'Käsmu', cidade: 'Käsmu', fora: true },
    { nome: 'Cidade universitária de Tartu', wiki: 'Tartu', cidade: 'Tartu', fora: true },
    { nome: 'Ilha de Hiiumaa (faróis históricos)', wiki: 'Hiiumaa', cidade: 'Kärdla', fora: true },
  ],
  ER: [
    { nome: 'Ilhas Dahlak', wiki: 'Dahlak Archipelago', cidade: 'Massawa', fora: true },
    { nome: 'Qohaito (sítio arqueológico)', wiki: 'Qohaito', cidade: 'Debub', fora: true },
    { nome: 'Keren (mercado de camelos)', wiki: 'Keren, Eritrea', cidade: 'Keren', fora: true },
    { nome: 'Adulis (ruínas antigas)', wiki: 'Adulis', cidade: 'Zula', fora: true },
    { nome: 'Filfil Solomuna (floresta)', wiki: 'Filfil Solomuna', cidade: 'Anseba', fora: true },
  ],
  ET: [
    { nome: 'Igrejas rupestres de Lalibela (Bete Giyorgis e secundárias)', wiki: 'Lalibela', cidade: 'Lalibela', fora: true },
    { nome: 'Vale do Omo (tribos Mursi e Hamer)', wiki: 'Omo River', cidade: 'Jinka', fora: true },
    { nome: 'Montanhas Bale (Parque Nacional)', wiki: 'Bale Mountains National Park', cidade: 'Goba', fora: true },
    { nome: 'Depressão de Danakil e vulcão Erta Ale', wiki: 'Erta Ale', cidade: 'Afar', fora: true },
    { nome: 'Harar Jugol (cidade amuralhada)', wiki: 'Harar', cidade: 'Harar', fora: true },
  ],
  FI: [
    { nome: 'Parque Nacional de Koli', wiki: 'Koli National Park', cidade: 'Lieksa', fora: true },
    { nome: 'Arquipélago de Åland', wiki: 'Åland Islands', cidade: 'Mariehamn', fora: true },
    { nome: 'Rovaniemi e Aldeia do Papai Noel (Lapônia rural)', wiki: 'Rovaniemi', cidade: 'Rovaniemi', fora: true },
    { nome: 'Parque Nacional de Nuuksio', wiki: 'Nuuksio National Park', cidade: 'Espoo', fora: true },
    { nome: 'Fortaleza de Olavinlinna em Savonlinna', wiki: 'Olavinlinna', cidade: 'Savonlinna', fora: true },
  ],
  FJ: [
    { nome: 'Ilhas Yasawa (vilarejos remotos)', wiki: 'Yasawa Islands', cidade: 'Yasawa', fora: true },
    { nome: 'Taveuni (Ilha do Jardim)', wiki: 'Taveuni', cidade: 'Taveuni', fora: true },
    { nome: 'Parque Nacional Bouma (Cachoeiras de Tavoro)', wiki: 'Bouma National Heritage Park', cidade: 'Taveuni', fora: true },
    { nome: 'Levuka (antiga capital colonial)', wiki: 'Levuka', cidade: 'Levuka', fora: true },
    { nome: 'Terras Altas de Navala (vila tradicional)', wiki: 'Navala', cidade: 'Ba', fora: true },
  ],
  FM: [
    { nome: 'Ruínas de Nan Madol', wiki: 'Nan Madol', cidade: 'Pohnpei', fora: true },
    { nome: 'Cachoeira Kepirohi', wiki: 'Kepirohi Waterfall', cidade: 'Pohnpei', fora: true },
    { nome: 'Ilha de Kosrae', wiki: 'Kosrae', cidade: 'Tofol', fora: true },
    { nome: 'Atol de Chuuk (mergulho em destroços da WWII)', wiki: 'Chuuk Lagoon', cidade: 'Weno', fora: true },
    { nome: 'Ilha de Yap (pedras Rai)', wiki: 'Rai stones', cidade: 'Colonia', fora: true },
  ],
  GA: [
    { nome: 'Parque Nacional de Loango (gorilas e elefantes na praia)', wiki: 'Loango National Park', cidade: 'Omboué', fora: true },
    { nome: 'Parque Nacional de Lopé', wiki: 'Lopé National Park', cidade: 'Lopé', fora: true },
    { nome: 'Reserva da Lagoa Iguela', wiki: 'Iguéla Lagoon', cidade: 'Omboué', fora: true },
    { nome: 'Cataratas de Kongou (Parque Nacional Ivindo)', wiki: 'Kongou Falls', cidade: 'Makokou', fora: true },
    { nome: 'Cidade colonial de Lambaréné (Hospital Albert Schweitzer)', wiki: 'Lambaréné', cidade: 'Lambaréné', fora: true },
  ],
  GD: [
    { nome: 'Reserva Florestal Grand Etang', wiki: 'Grand Etang National Park and Forest Reserve', cidade: 'Saint Andrew', fora: true },
    { nome: 'Cachoeiras de Concord', wiki: 'Concord Falls', cidade: 'Saint John', fora: true },
    { nome: 'Parque de Esculturas Subaquáticas de Molinere', wiki: 'Molinere Underwater Sculpture Park', cidade: 'Saint George\'s', fora: true },
    { nome: 'Ilha Carriacou', wiki: 'Carriacou', cidade: 'Hillsborough', fora: true },
    { nome: 'Lago de cratera Levera', wiki: 'Levera National Park', cidade: 'Saint Patrick', fora: true },
  ],
  GE: [
    { nome: 'Vilarejos de Ushguli (Svaneti)', wiki: 'Ushguli', cidade: 'Mestia', fora: true },
    { nome: 'Parque Nacional Vashlovani', wiki: 'Vashlovani National Park', cidade: 'Dedoplistsqaro', fora: true },
    { nome: 'Cidade caverna de Vardzia', wiki: 'Vardzia', cidade: 'Aspindza', fora: true },
    { nome: 'Vale de Tusheti', wiki: 'Tusheti', cidade: 'Omalo', fora: true },
    { nome: 'Reserva Lagodekhi', wiki: 'Lagodekhi Protected Areas', cidade: 'Lagodekhi', fora: true },
  ],
  GH: [
    { nome: 'Santuário de Macacos de Boabeng-Fiema', wiki: 'Boabeng-Fiema Monkey Sanctuary', cidade: 'Boabeng', fora: true },
    { nome: 'Parque Nacional Mole', wiki: 'Mole National Park', cidade: 'Damongo', fora: true },
    { nome: 'Mesquita de Larabanga', wiki: 'Larabanga Mosque', cidade: 'Larabanga', fora: true },
    { nome: 'Cachoeira de Wli', wiki: 'Wli Falls', cidade: 'Wli', fora: true },
    { nome: 'Vila de palafitas Nzulezu', wiki: 'Nzulezu', cidade: 'Beyin', fora: true },
  ],
  GM: [
    { nome: 'Reserva Natural de Abuko', wiki: 'Abuko Nature Reserve', cidade: 'Abuko', fora: true },
    { nome: 'Ilha Kunta Kinteh (James Island)', wiki: 'Kunta Kinteh Island', cidade: 'Juffureh', fora: true },
    { nome: 'Pedras de Wassu (Senegambian stone circles)', wiki: 'Senegambian stone circles', cidade: 'Wassu', fora: true },
    { nome: 'Vila de Janjanbureh (Georgetown)', wiki: 'Janjanbureh', cidade: 'Janjanbureh', fora: true },
    { nome: 'Parque Nacional do Rio Gambia', wiki: 'River Gambia National Park', cidade: 'Kuntaur', fora: true },
  ],
  GN: [
    { nome: 'Fouta Djallon (planalto)', wiki: 'Fouta Djallon', cidade: 'Labé', fora: true },
    { nome: 'Ilhas de Los', wiki: 'Loos Islands', cidade: 'Conakry', fora: true },
    { nome: 'Cataratas do Kinkon', wiki: 'Kinkon Falls', cidade: 'Pita', fora: true },
    { nome: 'Parque Nacional do Alto Níger', wiki: 'Upper Niger National Park', cidade: 'Faranah', fora: true },
    { nome: 'Véu da Noiva (Cachoeira de Ditinn)', wiki: 'Ditinn Falls', cidade: 'Dalaba', fora: true },
  ],
  GQ: [
    { nome: 'Ilha de Annobón', wiki: 'Annobón', cidade: 'Annobón', fora: true },
    { nome: 'Parque Nacional de Monte Alén', wiki: 'Monte Alén National Park', cidade: 'Niefang', fora: true },
    { nome: 'Reserva Científica da Caldeira de Luba', wiki: 'Luba Crater Scientific Reserve', cidade: 'Luba', fora: true },
    { nome: 'Ilha de Corisco', wiki: 'Corisco', cidade: 'Corisco', fora: true },
    { nome: 'Cataratas de Moca', wiki: 'Moca, Equatorial Guinea', cidade: 'Moca', fora: true },
  ],
  GT: [
    { nome: 'Vilarejo de San Juan La Laguna', wiki: 'San Juan La Laguna', cidade: 'Sololá', fora: true },
    { nome: 'Parque Nacional Semuc Champey', wiki: 'Semuc Champey', cidade: 'Lanquín', fora: true },
    { nome: 'Ruínas de Yaxhá', wiki: 'Yaxha', cidade: 'Petén', fora: true },
    { nome: 'Lagoa de Chicabal', wiki: 'Laguna Chicabal', cidade: 'Quetzaltenango', fora: true },
    { nome: 'Cidade colonial de Quetzaltenango (Xela)', wiki: 'Quetzaltenango', cidade: 'Quetzaltenango', fora: true },
  ],
  GW: [
    { nome: 'Arquipélago dos Bijagós', wiki: 'Bijagós Archipelago', cidade: 'Bubaque', fora: true },
    { nome: 'Parque Nacional de Cantanhez', wiki: 'Cantanhez Forests National Park', cidade: 'Tombali', fora: true },
    { nome: 'Ilha de Orango', wiki: 'Orango Island', cidade: 'Bolama', fora: true },
    { nome: 'Bolama (antiga capital colonial)', wiki: 'Bolama', cidade: 'Bolama', fora: true },
    { nome: 'Parque Nacional de Cufada', wiki: 'Lagoas de Cufada Natural Park', cidade: 'Buba', fora: true },
  ],
  GY: [
    { nome: 'Cataratas Kaieteur', wiki: 'Kaieteur Falls', cidade: 'Potaro-Siparuni', fora: true },
    { nome: 'Savana do Rupununi', wiki: 'Rupununi', cidade: 'Lethem', fora: true },
    { nome: 'Vila Ameríndia de Surama', wiki: 'Surama, Guyana', cidade: 'Surama', fora: true },
    { nome: 'Reserva Iwokrama', wiki: 'Iwokrama Forest', cidade: 'Kurupukari', fora: true },
    { nome: 'Cataratas Orinduik', wiki: 'Orinduik Falls', cidade: 'Potaro-Siparuni', fora: true },
  ],
  HK: [
    { nome: 'Vila de pescadores Tai O', wiki: 'Tai O', cidade: 'Lantau', fora: true },
    { nome: 'Ilha Cheung Chau', wiki: 'Cheung Chau', cidade: 'Cheung Chau', fora: true },
    { nome: 'Geopark de Hong Kong', wiki: 'Hong Kong UNESCO Global Geopark', cidade: 'Sai Kung', fora: true },
    { nome: 'Sai Kung (vila e parque)', wiki: 'Sai Kung Town', cidade: 'Sai Kung', fora: true },
    { nome: 'Mercado de Sham Shui Po', wiki: 'Sham Shui Po', cidade: 'Kowloon', fora: true },
  ],
  HN: [
    { nome: 'Ruínas Maias de Copán', wiki: 'Copán', cidade: 'Copán Ruinas', fora: true },
    { nome: 'Arquipélago de Cayos Cochinos', wiki: 'Cayos Cochinos', cidade: 'La Ceiba', fora: true },
    { nome: 'Parque Nacional Pico Bonito', wiki: 'Pico Bonito National Park', cidade: 'La Ceiba', fora: true },
    { nome: 'Lago de Yojoa', wiki: 'Lake Yojoa', cidade: 'Santa Cruz de Yojoa', fora: true },
    { nome: 'Reserva da Biosfera Río Plátano', wiki: 'Río Plátano Biosphere Reserve', cidade: 'Gracias a Dios', fora: true },
  ],
  HT: [
    { nome: 'Citadelle Laferrière', wiki: 'Citadelle Laferrière', cidade: 'Milot', fora: true },
    { nome: 'Bassin Bleu (cachoeiras)', wiki: 'Bassin Bleu', cidade: 'Jacmel', fora: true },
    { nome: 'Parque Nacional La Visite', wiki: 'La Visite National Park', cidade: 'Seguin', fora: true },
    { nome: 'Cidade colonial de Jacmel', wiki: 'Jacmel', cidade: 'Jacmel', fora: true },
    { nome: 'Île-à-Vache', wiki: 'Île-à-Vache', cidade: 'Les Cayes', fora: true },
  ],
  HU: [
    { nome: 'Cidade barroca de Eger', wiki: 'Eger', cidade: 'Eger', fora: true },
    { nome: 'Parque Nacional Hortobágy', wiki: 'Hortobágy National Park', cidade: 'Hortobágy', fora: true },
    { nome: 'Pécs (cidade histórica)', wiki: 'Pécs', cidade: 'Pécs', fora: true },
    { nome: 'Caverna Aggtelek (Baradla)', wiki: 'Aggtelek National Park', cidade: 'Aggtelek', fora: true },
    { nome: 'Lago Tisza', wiki: 'Lake Tisza', cidade: 'Poroszló', fora: true },
  ],
  IE: [
    { nome: 'Península de Dingle (Slea Head)', wiki: 'Dingle Peninsula', cidade: 'Kerry', fora: true },
    { nome: 'Ilhas Aran (Inis Mór, Dún Aonghasa)', wiki: 'Aran Islands', cidade: 'Galway', fora: true },
    { nome: 'Skellig Michael (mosteiro monástico)', wiki: 'Skellig Michael', cidade: 'Kerry', fora: true },
    { nome: 'Burren (planalto cárstico)', wiki: 'The Burren', cidade: 'Clare', fora: true },
    { nome: 'Glendalough (vale monástico em Wicklow)', wiki: 'Glendalough', cidade: 'Wicklow', fora: true },
  ],
  IQ: [
    { nome: 'Marismas da Mesopotâmia', wiki: 'Mesopotamian Marshes', cidade: 'Basra', fora: true },
    { nome: 'Hatra (cidade arqueológica)', wiki: 'Hatra', cidade: 'Nínive', fora: true },
    { nome: 'Cidadela de Erbil', wiki: 'Erbil Citadel', cidade: 'Erbil', fora: true },
    { nome: 'Lalish (templo yazidi)', wiki: 'Lalish', cidade: 'Duhok', fora: true },
    { nome: 'Amadiya (cidade nas montanhas)', wiki: 'Amadiya', cidade: 'Duhok', fora: true },
  ],
  IR: [
    { nome: 'Vilarejo de Masuleh (casas em terraços)', wiki: 'Masuleh', cidade: 'Gilan', fora: true },
    { nome: 'Kandovan (casas trogloditas)', wiki: 'Kandovan', cidade: 'Tabriz', fora: true },
    { nome: 'Ilha de Hormuz (Vale dos Arco-íris)', wiki: 'Hormuz Island', cidade: 'Hormozgan', fora: true },
    { nome: 'Deserto de Lut (Kaluts)', wiki: 'Dasht-e Lut', cidade: 'Kerman', fora: true },
    { nome: 'Cidade antiga de Yazd (arquitetura adobe)', wiki: 'Yazd', cidade: 'Yazd', fora: true },
  ],
  IS: [
    { nome: 'Península de Snæfellsnes', wiki: 'Snæfellsnes', cidade: 'Stykkishólmur', fora: true },
    { nome: 'Fiordes do Oeste (Westfjords)', wiki: 'Westfjords', cidade: 'Ísafjörður', fora: true },
    { nome: 'Reserva Natural de Hornstrandir', wiki: 'Hornstrandir', cidade: 'Ísafjörður', fora: true },
    { nome: 'Vale de Þórsmörk', wiki: 'Þórsmörk', cidade: 'Hvolsvöllur', fora: true },
    { nome: 'Ilhas Westman (Vestmannaeyjar)', wiki: 'Vestmannaeyjar', cidade: 'Heimaey', fora: true },
  ],
  JM: [
    { nome: 'Vilarejo de Treasure Beach', wiki: 'Treasure Beach', cidade: 'Saint Elizabeth', fora: true },
    { nome: 'Port Antonio e Blue Lagoon', wiki: 'Port Antonio', cidade: 'Port Antonio', fora: true },
    { nome: 'Montanhas Blue and John Crow', wiki: 'Blue and John Crow Mountains National Park', cidade: 'Kingston', fora: true },
    { nome: 'Cataratas de Reach Falls', wiki: 'Reach Falls', cidade: 'Manchioneal', fora: true },
    { nome: 'Vila pesqueira de Bluefields', wiki: 'Bluefields, Jamaica', cidade: 'Westmoreland', fora: true },
  ],
  JO: [
    { nome: 'Reserva de Dana Biosphere', wiki: 'Dana Biosphere Reserve', cidade: 'Tafilah', fora: true },
    { nome: 'Castelo de Ajloun', wiki: 'Ajloun Castle', cidade: 'Ajloun', fora: true },
    { nome: 'Umm Qais (Gadara)', wiki: 'Umm Qais', cidade: 'Irbid', fora: true },
    { nome: 'Reserva de Azraq Wetland', wiki: 'Azraq Wetland Reserve', cidade: 'Azraq', fora: true },
    { nome: 'Castelos do deserto (Qasr Amra)', wiki: 'Qasr Amra', cidade: 'Zarqa', fora: true },
  ],
  KE: [
    { nome: 'Reserva Nacional de Samburu', wiki: 'Samburu National Reserve', cidade: 'Samburu', fora: true },
    { nome: 'Ilha de Lamu (cidade velha)', wiki: 'Lamu Old Town', cidade: 'Lamu', fora: true },
    { nome: 'Lago Turkana', wiki: 'Lake Turkana', cidade: 'Lodwar', fora: true },
    { nome: 'Parque Nacional do Monte Quênia', wiki: 'Mount Kenya National Park', cidade: 'Nanyuki', fora: true },
    { nome: 'Floresta de Kakamega', wiki: 'Kakamega Forest', cidade: 'Kakamega', fora: true },
  ],
  KG: [
    { nome: 'Lago Song-Kol', wiki: 'Song Kol Lake', cidade: 'Naryn', fora: true },
    { nome: 'Vale de Arslanbob', wiki: 'Arslanbob', cidade: 'Jalal-Abad', fora: true },
    { nome: 'Torre de Burana', wiki: 'Burana Tower', cidade: 'Tokmok', fora: true },
    { nome: 'Vale de Jeti-Ögüz', wiki: 'Jeti-Ögüz', cidade: 'Karakol', fora: true },
    { nome: 'Parque Nacional Sary-Chelek', wiki: 'Sary-Chelek Nature Reserve', cidade: 'Jalal-Abad', fora: true },
  ],
  KH: [
    { nome: 'Templo Preah Vihear', wiki: 'Preah Vihear Temple', cidade: 'Preah Vihear', fora: true },
    { nome: 'Templo Banteay Chhmar', wiki: 'Banteay Chhmar', cidade: 'Banteay Meanchey', fora: true },
    { nome: 'Ilha de Koh Rong Samloem', wiki: 'Koh Rong Sanloem', cidade: 'Sihanoukville', fora: true },
    { nome: 'Cachoeiras de Kbal Chhay', wiki: 'Kbal Chhay Waterfalls', cidade: 'Sihanoukville', fora: true },
    { nome: 'Battambang (cidade colonial)', wiki: 'Battambang', cidade: 'Battambang', fora: true },
  ],
  KI: [
    { nome: 'Atol de Abaiang', wiki: 'Abaiang', cidade: 'Abaiang', fora: true },
    { nome: 'Ilha Abemama', wiki: 'Abemama', cidade: 'Abemama', fora: true },
    { nome: 'Ilha Banaba (Ocean Island)', wiki: 'Banaba Island', cidade: 'Banaba', fora: true },
    { nome: 'Ilha Kiritimati (Christmas Island)', wiki: 'Kiritimati', cidade: 'Kiritimati', fora: true },
    { nome: 'Área de Conservação das Ilhas Phoenix', wiki: 'Phoenix Islands Protected Area', cidade: 'Kanton', fora: true },
  ],
  KM: [
    { nome: 'Monte Karthala', wiki: 'Mount Karthala', cidade: 'Moroni', fora: true },
    { nome: 'Ilha de Mohéli (Mwali)', wiki: 'Mohéli', cidade: 'Fomboni', fora: true },
    { nome: 'Parque Marinho de Mohéli', wiki: 'Mohéli Marine Park', cidade: 'Nioumachoua', fora: true },
    { nome: 'Lago Salgado de Dziani Dzaha', wiki: 'Lake Dziani Dzaha', cidade: 'Mitsamiouli', fora: true },
    { nome: 'Medina de Mutsamudu', wiki: 'Mutsamudu', cidade: 'Mutsamudu', fora: true },
  ],
  KN: [
    { nome: 'Romney Manor e Wingfield Estate', wiki: 'Romney Manor', cidade: 'Old Road Town', fora: true },
    { nome: 'Vila de Dieppe Bay Town', wiki: 'Dieppe Bay Town', cidade: 'Dieppe Bay', fora: true },
    { nome: 'Mount Liamuiga (vulcão e trilha)', wiki: 'Mount Liamuiga', cidade: 'Saint Paul Capisterre', fora: true },
    { nome: 'Charlestown (capital de Nevis)', wiki: 'Charlestown, Nevis', cidade: 'Charlestown', fora: true },
    { nome: 'Nevis Peak (trilha vulcânica)', wiki: 'Nevis Peak', cidade: 'Charlestown', fora: true },
  ],
  KP: [
    { nome: 'Monte Myohyang', wiki: 'Mount Myohyang', cidade: 'Hyangsan', fora: true },
    { nome: 'Monte Chilbo', wiki: 'Mount Chilbo', cidade: 'Myongchon', fora: true },
    { nome: 'Cidade de Kaesong', wiki: 'Kaesong', cidade: 'Kaesong', fora: true },
    { nome: 'Cidade portuária de Wonsan', wiki: 'Wonsan', cidade: 'Wonsan', fora: true },
    { nome: 'Tumba do Rei Tongmyong', wiki: 'Tomb of King Tongmyong', cidade: 'Pyongyang', fora: true },
  ],
  KW: [
    { nome: 'Ilha Failaka', wiki: 'Failaka Island', cidade: 'Failaka', fora: true },
    { nome: 'Reserva Natural Al Jahra Pools', wiki: 'Jahra', cidade: 'Jahra', fora: true },
    { nome: 'Casa Sadu (artesanato beduíno)', wiki: 'Sadu House', cidade: 'Cidade do Kuwait', fora: true },
    { nome: 'Mercado Souq Al-Mubarakiya', wiki: 'Souq Al-Mubarakiya', cidade: 'Cidade do Kuwait', fora: true },
    { nome: 'Museu Tareq Rajab', wiki: 'Tareq Rajab Museum', cidade: 'Cidade do Kuwait', fora: true },
  ],
  KZ: [
    { nome: 'Cânion de Charyn', wiki: 'Charyn Canyon', cidade: 'Almaty', fora: true },
    { nome: 'Lago Kaindy (árvores submersas)', wiki: 'Kaindy Lake', cidade: 'Almaty', fora: true },
    { nome: 'Mausoléu de Khoja Ahmed Yasawi (Turquestão)', wiki: 'Mausoleum of Khoja Ahmed Yasawi', cidade: 'Turquestão', fora: true },
    { nome: 'Parque Nacional Altyn-Emel', wiki: 'Altyn-Emel National Park', cidade: 'Almaty', fora: true },
    { nome: 'Necrópole de Beket-Ata (Mangystau)', wiki: 'Beket-Ata', cidade: 'Mangystau', fora: true },
  ],
  LA: [
    { nome: 'Plateau de Bolaven', wiki: 'Bolaven Plateau', cidade: 'Champasak', fora: true },
    { nome: '4000 Ilhas (Si Phan Don)', wiki: 'Si Phan Don', cidade: 'Champasak', fora: true },
    { nome: 'Planície dos Jarros', wiki: 'Plain of Jars', cidade: 'Xiangkhouang', fora: true },
    { nome: 'Nong Khiaw', wiki: 'Nong Khiaw', cidade: 'Luang Prabang', fora: true },
    { nome: 'Cavernas de Vieng Xai', wiki: 'Vieng Xai', cidade: 'Houaphanh', fora: true },
  ],
  LB: [
    { nome: 'Vale do Qadisha', wiki: 'Kadisha Valley', cidade: 'Bsharri', fora: true },
    { nome: 'Floresta dos Cedros de Deus', wiki: 'Cedars of God', cidade: 'Bsharri', fora: true },
    { nome: 'Cidade antiga de Tiro', wiki: 'Tyre, Lebanon', cidade: 'Tiro', fora: true },
    { nome: 'Grutas de Jeita', wiki: 'Jeita Grotto', cidade: 'Jeita', fora: true },
    { nome: 'Vilarejo de Douma', wiki: 'Douma, Lebanon', cidade: 'Douma', fora: true },
  ],
  LC: [
    { nome: 'Vila de pescadores de Anse La Raye', wiki: 'Anse la Raye Quarter', cidade: 'Anse La Raye', fora: true },
    { nome: 'Reserva Natural Maria Islands', wiki: 'Maria Islands Nature Reserve', cidade: 'Vieux Fort', fora: true },
    { nome: 'Cachoeiras de Toraille', wiki: 'Toraille Waterfall', cidade: 'Soufrière', fora: true },
    { nome: 'Trilha do Parque Nacional Pigeon Island', wiki: 'Pigeon Island (Saint Lucia)', cidade: 'Gros Islet', fora: true },
    { nome: 'Vila de Canaries', wiki: 'Canaries, Saint Lucia', cidade: 'Canaries', fora: true },
  ],
  LI: [
    { nome: 'Trilha Fürstensteig (Alpes liechtensteinianos)', wiki: 'Fürstensteig', cidade: 'Triesenberg', fora: true },
    { nome: 'Vilarejo alpino de Malbun', wiki: 'Malbun', cidade: 'Triesenberg', fora: true },
    { nome: 'Aldeia histórica de Triesenberg (Walser)', wiki: 'Triesenberg', cidade: 'Triesenberg', fora: true },
    { nome: 'Ruínas do Castelo de Schellenberg', wiki: 'Schellenberg', cidade: 'Schellenberg', fora: true },
    { nome: 'Reserva natural de Ruggeller Riet', wiki: 'Ruggeller Riet', cidade: 'Ruggell', fora: true },
  ],
  LR: [
    { nome: 'Parque Nacional Sapo', wiki: 'Sapo National Park', cidade: 'Sinoe', fora: true },
    { nome: 'Cidade de Robertsport', wiki: 'Robertsport', cidade: 'Robertsport', fora: true },
    { nome: 'Lago Piso', wiki: 'Lake Piso', cidade: 'Robertsport', fora: true },
    { nome: 'Floresta Nacional de Gola', wiki: 'Gola Forest National Park', cidade: 'Lofa', fora: true },
    { nome: 'Praia de Buchanan', wiki: 'Buchanan, Liberia', cidade: 'Buchanan', fora: true },
  ],
  LS: [
    { nome: 'Parque Nacional Ts\'ehlanyane', wiki: 'Ts\'ehlanyane National Park', cidade: 'Butha-Buthe', fora: true },
    { nome: 'Vilarejo de Malealea', wiki: 'Malealea', cidade: 'Mafeteng', fora: true },
    { nome: 'Cachoeira Maletsunyane', wiki: 'Maletsunyane Falls', cidade: 'Semonkong', fora: true },
    { nome: 'Represa de Katse', wiki: 'Katse Dam', cidade: 'Thaba-Tseka', fora: true },
    { nome: 'Pinturas rupestres de Liphofung', wiki: 'Liphofung', cidade: 'Butha-Buthe', fora: true },
  ],
  LT: [
    { nome: 'Istmo da Curlândia (Neringa)', wiki: 'Curonian Spit', cidade: 'Neringa', fora: true },
    { nome: 'Parque Nacional de Aukštaitija', wiki: 'Aukštaitija National Park', cidade: 'Ignalina', fora: true },
    { nome: 'Colina das Cruzes', wiki: 'Hill of Crosses', cidade: 'Šiauliai', fora: true },
    { nome: 'Castelo da Ilha de Trakai', wiki: 'Trakai Island Castle', cidade: 'Trakai', fora: true },
    { nome: 'República autoproclamada de Užupis', wiki: 'Užupis', cidade: 'Vilnius', fora: true },
  ],
  LU: [
    { nome: 'Trilhas do Mullerthal (Pequena Suíça Luxemburguesa)', wiki: 'Mullerthal Trail', cidade: 'Echternach', fora: true },
    { nome: 'Vale dos Sete Castelos', wiki: 'Valley of the Seven Castles', cidade: 'Mersch', fora: true },
    { nome: 'Cidade medieval de Vianden', wiki: 'Vianden', cidade: 'Vianden', fora: true },
    { nome: 'Vilarejo vinícola de Remich (Vale do Mosela)', wiki: 'Remich', cidade: 'Remich', fora: true },
    { nome: 'Minas de ardósia de Esch-sur-Sûre', wiki: 'Esch-sur-Sûre', cidade: 'Esch-sur-Sûre', fora: true },
  ],
  LV: [
    { nome: 'Parque Nacional Gauja', wiki: 'Gauja National Park', cidade: 'Sigulda', fora: true },
    { nome: 'Cidade de Kuldīga (cascata Ventas Rumba)', wiki: 'Kuldīga', cidade: 'Kuldīga', fora: true },
    { nome: 'Cabo Kolka (Parque Nacional Slītere)', wiki: 'Cape Kolka', cidade: 'Kolka', fora: true },
    { nome: 'Vilarejo Líbio de Mazirbe', wiki: 'Mazirbe', cidade: 'Dundaga', fora: true },
    { nome: 'Castelo de Cēsis', wiki: 'Cēsis Castle', cidade: 'Cēsis', fora: true },
  ],
  LY: [
    { nome: 'Sítio arqueológico de Cirene', wiki: 'Cyrene, Libya', cidade: 'Shahhat', fora: true },
    { nome: 'Ruínas de Sabratha', wiki: 'Sabratha', cidade: 'Sabratha', fora: true },
    { nome: 'Cidade antiga de Ghadames', wiki: 'Ghadames', cidade: 'Ghadames', fora: true },
    { nome: 'Pinturas rupestres de Tadrart Acacus', wiki: 'Tadrart Acacus', cidade: 'Ghat', fora: true },
    { nome: 'Oásis de Awbari', wiki: 'Ubari', cidade: 'Ubari', fora: true },
  ],
  MC: [
    { nome: 'Jardim Exótico de Mônaco', wiki: 'Jardin Exotique de Monaco', cidade: 'Monaco', fora: true },
    { nome: 'Museu de Antropologia Pré-histórica', wiki: 'Museum of Prehistoric Anthropology of Monaco', cidade: 'Monaco', fora: true },
    { nome: 'Bairro de Fontvieille', wiki: 'Fontvieille, Monaco', cidade: 'Fontvieille', fora: true },
    { nome: 'Capela da Misericórdia', wiki: 'Chapel of Mercy, Monaco', cidade: 'Monaco-Ville', fora: true },
    { nome: 'Coleção de Carros do Príncipe', wiki: 'Prince of Monaco\'s Car Collection', cidade: 'Fontvieille', fora: true },
  ],
  MD: [
    { nome: 'Mosteiro rupestre de Orheiul Vechi', wiki: 'Orheiul Vechi', cidade: 'Trebujeni', fora: true },
    { nome: 'Adega subterrânea de Mileștii Mici', wiki: 'Mileștii Mici', cidade: 'Mileștii Mici', fora: true },
    { nome: 'Transnístria (Tiraspol)', wiki: 'Tiraspol', cidade: 'Tiraspol', fora: true },
    { nome: 'Fortaleza de Soroca', wiki: 'Soroca Fort', cidade: 'Soroca', fora: true },
    { nome: 'Reserva natural Codru', wiki: 'Codrii Nature Reserve', cidade: 'Lozova', fora: true },
  ],
  ME: [
    { nome: 'Parque Nacional Durmitor', wiki: 'Durmitor', cidade: 'Žabljak', fora: true },
    { nome: 'Vila de Perast', wiki: 'Perast', cidade: 'Perast', fora: true },
    { nome: 'Mosteiro de Ostrog', wiki: 'Ostrog Monastery', cidade: 'Nikšić', fora: true },
    { nome: 'Lago Skadar', wiki: 'Lake Skadar', cidade: 'Virpazar', fora: true },
    { nome: 'Vila histórica de Njeguši', wiki: 'Njeguši', cidade: 'Njeguši', fora: true },
  ],
  MG: [
    { nome: 'Parque Nacional Ranomafana', wiki: 'Ranomafana National Park', cidade: 'Fianarantsoa', fora: true },
    { nome: 'Reserva de Anja', wiki: 'Anja Community Reserve', cidade: 'Ambalavao', fora: true },
    { nome: 'Parque Nacional Andringitra', wiki: 'Andringitra National Park', cidade: 'Ambalavao', fora: true },
    { nome: 'Ilha de Sainte-Marie', wiki: 'Île Sainte-Marie', cidade: 'Sainte-Marie', fora: true },
    { nome: 'Parque Nacional Masoala', wiki: 'Masoala National Park', cidade: 'Maroantsetra', fora: true },
  ],
  MH: [
    { nome: 'Atol de Bikini', wiki: 'Bikini Atoll', cidade: 'Bikini', fora: true },
    { nome: 'Atol de Arno', wiki: 'Arno Atoll', cidade: 'Arno', fora: true },
    { nome: 'Atol de Mili', wiki: 'Mili Atoll', cidade: 'Mili', fora: true },
    { nome: 'Atol de Rongelap', wiki: 'Rongelap Atoll', cidade: 'Rongelap', fora: true },
    { nome: 'Atol de Wotje', wiki: 'Wotje Atoll', cidade: 'Wotje', fora: true },
  ],
  MK: [
    { nome: 'Lago Prespa e Ilha Golem Grad', wiki: 'Golem Grad', cidade: 'Resen', fora: true },
    { nome: 'Vila de Vevčani e suas nascentes', wiki: 'Vevčani', cidade: 'Vevčani', fora: true },
    { nome: 'Monastério de Bigorski', wiki: 'Bigorski Monastery', cidade: 'Debar', fora: true },
    { nome: 'Cânion Matka', wiki: 'Matka Canyon', cidade: 'Skopje', fora: true },
    { nome: 'Cidade antiga de Stobi', wiki: 'Stobi', cidade: 'Gradsko', fora: true },
  ],
  ML: [
    { nome: 'Falésia de Bandiagara (País Dogon)', wiki: 'Bandiagara Escarpment', cidade: 'Bandiagara', fora: true },
    { nome: 'Mesquita de Djenné', wiki: 'Great Mosque of Djenné', cidade: 'Djenné', fora: true },
    { nome: 'Tumba dos Askia', wiki: 'Tomb of Askia', cidade: 'Gao', fora: true },
    { nome: 'Reserva de Elefantes de Gourma', wiki: 'Gourma elephants', cidade: 'Douentza', fora: true },
    { nome: 'Kayes (forte colonial e cataratas de Félou)', wiki: 'Kayes', cidade: 'Kayes', fora: true },
  ],
  MM: [
    { nome: 'Lago Inle e vilarejos palafitas', wiki: 'Inle Lake', cidade: 'Nyaungshwe', fora: true },
    { nome: 'Mrauk U (ruínas arqueológicas)', wiki: 'Mrauk U', cidade: 'Mrauk U', fora: true },
    { nome: 'Hsipaw (trilhas e tribos Shan)', wiki: 'Hsipaw', cidade: 'Hsipaw', fora: true },
    { nome: 'Cavernas de Pindaya', wiki: 'Pindaya Caves', cidade: 'Pindaya', fora: true },
    { nome: 'Kalaw (cidade colonial e trekking)', wiki: 'Kalaw', cidade: 'Kalaw', fora: true },
  ],
  MN: [
    { nome: 'Parque Nacional Gorkhi-Terelj', wiki: 'Gorkhi-Terelj National Park', cidade: 'Töv', fora: true },
    { nome: 'Lago Khövsgöl', wiki: 'Lake Khövsgöl', cidade: 'Khatgal', fora: true },
    { nome: 'Vale de Orkhon', wiki: 'Orkhon Valley', cidade: 'Kharkhorin', fora: true },
    { nome: 'Deserto de Gobi - Bayanzag (Flaming Cliffs)', wiki: 'Bayanzag', cidade: 'Bulgan', fora: true },
    { nome: 'Tsenkher Hot Springs', wiki: 'Tsenkher hot springs', cidade: 'Arkhangai', fora: true },
  ],
  MO: [
    { nome: 'Vilarejo de Coloane', wiki: 'Coloane', cidade: 'Coloane', fora: true },
    { nome: 'Vilarejo de Taipa', wiki: 'Taipa Village', cidade: 'Taipa', fora: true },
    { nome: 'Templo A-Má', wiki: 'A-Ma Temple', cidade: 'Macau', fora: true },
    { nome: 'Fortaleza do Monte (Museu de Macau)', wiki: 'Mount Fortress', cidade: 'Macau', fora: true },
    { nome: 'Farol da Guia', wiki: 'Guia Fortress', cidade: 'Macau', fora: true },
  ],
  MR: [
    { nome: 'Banc d\'Arguin (Parque Nacional)', wiki: 'Banc d\'Arguin National Park', cidade: 'Nouadhibou', fora: true },
    { nome: 'Oualata (cidade caravaneira)', wiki: 'Oualata', cidade: 'Oualata', fora: true },
    { nome: 'Tichitt (vilarejo medieval)', wiki: 'Tichitt', cidade: 'Tichitt', fora: true },
    { nome: 'Terjit (oásis no Adrar)', wiki: 'Terjit', cidade: 'Atar', fora: true },
    { nome: 'Cemitério de navios de Nouadhibou', wiki: 'Nouadhibou', cidade: 'Nouadhibou', fora: true },
  ],
  MT: [
    { nome: 'Ilha de Comino e Lagoa Azul', wiki: 'Comino', cidade: 'Comino', fora: true },
    { nome: 'Cidade silenciosa de Mdina', wiki: 'Mdina', cidade: 'Mdina', fora: true },
    { nome: 'Templos de Ġgantija', wiki: 'Ġgantija', cidade: 'Xagħra', fora: true },
    { nome: 'Vila de pescadores de Marsaxlokk', wiki: 'Marsaxlokk', cidade: 'Marsaxlokk', fora: true },
    { nome: 'Hipogeu de Ħal-Saflieni', wiki: 'Ħal-Saflieni Hypogeum', cidade: 'Paola', fora: true },
  ],
  MU: [
    { nome: 'Parque Nacional Black River Gorges', wiki: 'Black River Gorges National Park', cidade: 'Rivière Noire', fora: true },
    { nome: 'Terras Coloridas de Chamarel', wiki: 'Chamarel', cidade: 'Chamarel', fora: true },
    { nome: 'Ilha dos Cervos (Île aux Cerfs)', wiki: 'Île aux Cerfs', cidade: 'Trou d\'Eau Douce', fora: true },
    { nome: 'Mercado central de Port Louis', wiki: 'Port Louis', cidade: 'Port Louis', fora: true },
    { nome: 'Vilarejo de Mahébourg', wiki: 'Mahébourg', cidade: 'Mahébourg', fora: true },
  ],
  MV: [
    { nome: 'Atol Baa (Reserva da Biosfera UNESCO)', wiki: 'Baa Atoll', cidade: 'Eydhafushi', fora: true },
    { nome: 'Ilha de Fuvahmulah', wiki: 'Fuvahmulah', cidade: 'Fuvahmulah', fora: true },
    { nome: 'Ilha local de Maafushi', wiki: 'Maafushi', cidade: 'Maafushi', fora: true },
    { nome: 'Atol de Addu (Gan)', wiki: 'Addu Atoll', cidade: 'Hithadhoo', fora: true },
    { nome: 'Ilha de Thoddoo', wiki: 'Thoddoo (Alif Alif Atoll)', cidade: 'Thoddoo', fora: true },
  ],
  MW: [
    { nome: 'Planalto de Nyika', wiki: 'Nyika National Park', cidade: 'Rumphi', fora: true },
    { nome: 'Reserva Florestal de Mulanje', wiki: 'Mount Mulanje', cidade: 'Mulanje', fora: true },
    { nome: 'Reserva de Caça de Majete', wiki: 'Majete Wildlife Reserve', cidade: 'Chikwawa', fora: true },
    { nome: 'Ilha de Likoma', wiki: 'Likoma Island', cidade: 'Likoma', fora: true },
    { nome: 'Vila histórica de Livingstonia', wiki: 'Livingstonia', cidade: 'Rumphi', fora: true },
  ],
  MY: [
    { nome: 'Parque Nacional Taman Negara', wiki: 'Taman Negara', cidade: 'Pahang', fora: true },
    { nome: 'Ilhas Perhentian', wiki: 'Perhentian Islands', cidade: 'Terengganu', fora: true },
    { nome: 'Vilarejo de Kampung Annah Rais', wiki: 'Annah Rais Bidayuh Longhouse', cidade: 'Kuching', fora: true },
    { nome: 'Ipoh (cidade colonial)', wiki: 'Ipoh', cidade: 'Perak', fora: true },
    { nome: 'Vale de Danum', wiki: 'Danum Valley Conservation Area', cidade: 'Sabah', fora: true },
  ],
  MZ: [
    { nome: 'Arquipélago de Bazaruto', wiki: 'Bazaruto Archipelago', cidade: 'Vilanculos', fora: true },
    { nome: 'Ilha de Moçambique', wiki: 'Ilha de Moçambique', cidade: 'Ilha de Moçambique', fora: true },
    { nome: 'Parque Nacional da Gorongosa', wiki: 'Gorongosa National Park', cidade: 'Sofala', fora: true },
    { nome: 'Arquipélago das Quirimbas', wiki: 'Quirimbas Archipelago', cidade: 'Pemba', fora: true },
    { nome: 'Praia do Tofo', wiki: 'Tofo', cidade: 'Inhambane', fora: true },
  ],
  NA: [
    { nome: 'Deserto do Kaokoland', wiki: 'Kaokoland', cidade: 'Opuwo', fora: true },
    { nome: 'Vila de Twyfelfontein', wiki: 'Twyfelfontein', cidade: 'Kunene', fora: true },
    { nome: 'Parque Nacional de Khaudum', wiki: 'Khaudum National Park', cidade: 'Tsumkwe', fora: true },
    { nome: 'Cidade fantasma de Kolmanskop', wiki: 'Kolmanskop', cidade: 'Lüderitz', fora: true },
    { nome: 'Floresta Petrificada de Damaraland', wiki: 'Petrified Forest (Namibia)', cidade: 'Khorixas', fora: true },
  ],
  NC: [
    { nome: 'Ilha dos Pinheiros (Île des Pins)', wiki: 'Île des Pins', cidade: 'Île des Pins', fora: true },
    { nome: 'Vale de Hienghène e penhascos calcários', wiki: 'Hienghène', cidade: 'Hienghène', fora: true },
    { nome: 'Parque Provincial da Rivière Bleue', wiki: 'Rivière Bleue Provincial Park', cidade: 'Yaté', fora: true },
    { nome: 'Ilha de Ouvéa (atol das Loyalty)', wiki: 'Ouvéa', cidade: 'Ouvéa', fora: true },
    { nome: 'Coração de Voh (manguezal aéreo)', wiki: 'Heart of Voh', cidade: 'Voh', fora: true },
  ],
  NE: [
    { nome: 'Reserva Natural Nacional do Aïr e Ténéré', wiki: 'Aïr and Ténéré National Nature Reserve', cidade: 'Agadez', fora: true },
    { nome: 'Cidade histórica de Agadez (centro antigo)', wiki: 'Historic Centre of Agadez', cidade: 'Agadez', fora: true },
    { nome: 'Parque Nacional do W', wiki: 'W National Park', cidade: 'Tillabéri', fora: true },
    { nome: 'Reserva de Girafas de Koure', wiki: 'Kouré', cidade: 'Kouré', fora: true },
    { nome: 'Zinder (antiga capital e medina)', wiki: 'Zinder', cidade: 'Zinder', fora: true },
  ],
  NG: [
    { nome: 'Montes Mambilla', wiki: 'Mambilla Plateau', cidade: 'Taraba', fora: true },
    { nome: 'Parque Nacional Yankari', wiki: 'Yankari National Park', cidade: 'Bauchi', fora: true },
    { nome: 'Floresta Sagrada de Osun-Osogbo', wiki: 'Osun-Osogbo Sacred Grove', cidade: 'Osogbo', fora: true },
    { nome: 'Colinas de Idanre', wiki: 'Idanre Hills', cidade: 'Idanre', fora: true },
    { nome: 'Cidade antiga de Sukur', wiki: 'Sukur', cidade: 'Adamawa', fora: true },
  ],
  NI: [
    { nome: 'Ilha de Ometepe', wiki: 'Ometepe', cidade: 'Rivas', fora: true },
    { nome: 'Reserva Natural Miraflor', wiki: 'Miraflor Natural Reserve', cidade: 'Estelí', fora: true },
    { nome: 'Arquipélago de Solentiname', wiki: 'Solentiname Islands', cidade: 'San Carlos', fora: true },
    { nome: 'Vulcão Cerro Negro', wiki: 'Cerro Negro', cidade: 'León', fora: true },
    { nome: 'Pueblos Blancos', wiki: 'Pueblos Blancos (Nicaragua)', cidade: 'Masaya', fora: true },
  ],
  NO: [
    { nome: 'Ilhas Lofoten (Reine)', wiki: 'Reine', cidade: 'Reine', fora: true },
    { nome: 'Arquipélago de Vesterålen', wiki: 'Vesterålen', cidade: 'Sortland', fora: true },
    { nome: 'Vila de Røros', wiki: 'Røros', cidade: 'Røros', fora: true },
    { nome: 'Parque Nacional Jotunheimen', wiki: 'Jotunheimen', cidade: 'Lom', fora: true },
    { nome: 'Ilha de Senja', wiki: 'Senja', cidade: 'Troms', fora: true },
  ],
  NR: [
    { nome: 'Lagoa Buada', wiki: 'Buada Lagoon', cidade: 'Buada', fora: true },
    { nome: 'Anibare Bay', wiki: 'Anibare Bay', cidade: 'Anibare', fora: true },
    { nome: 'Command Ridge (bunkers japoneses da WWII)', wiki: 'Command Ridge', cidade: 'Aiwo', fora: true },
    { nome: 'Moqua Caves e Moqua Well', wiki: 'Moqua Well', cidade: 'Yaren', fora: true },
    { nome: 'Distrito de Yaren (capital de facto)', wiki: 'Yaren District', cidade: 'Yaren', fora: true },
  ],
  NZ: [
    { nome: 'Península de Coromandel', wiki: 'Coromandel Peninsula', cidade: 'Thames', fora: true },
    { nome: 'Parque Nacional Abel Tasman', wiki: 'Abel Tasman National Park', cidade: 'Mārahau', fora: true },
    { nome: 'Cidade gótica de Oamaru', wiki: 'Oamaru', cidade: 'Oamaru', fora: true },
    { nome: 'Catlins (costa selvagem do sul)', wiki: 'The Catlins', cidade: 'Owaka', fora: true },
    { nome: 'Stewart Island / Rakiura', wiki: 'Stewart Island', cidade: 'Oban', fora: true },
  ],
  OM: [
    { nome: 'Vilarejo montanhês de Misfat al Abriyeen', wiki: 'Misfat Al Abriyeen', cidade: 'Al Hamra', fora: true },
    { nome: 'Wadi Shab', wiki: 'Wadi Shab', cidade: 'Tiwi', fora: true },
    { nome: 'Jebel Akhdar (montanha verde)', wiki: 'Jebel Akhdar (Oman)', cidade: 'Nizwa', fora: true },
    { nome: 'Forte de Bahla', wiki: 'Bahla Fort', cidade: 'Bahla', fora: true },
    { nome: 'Wahiba Sands (deserto dos beduínos)', wiki: 'Sharqiya Sands', cidade: 'Bidiyah', fora: true },
  ],
  PA: [
    { nome: 'Arquipélago de San Blas (Guna Yala)', wiki: 'Guna Yala', cidade: 'Guna Yala', fora: true },
    { nome: 'Parque Nacional Coiba', wiki: 'Coiba National Park', cidade: 'Santiago de Veraguas', fora: true },
    { nome: 'Vale de Antón (cratera vulcânica)', wiki: 'El Valle de Antón', cidade: 'El Valle de Antón', fora: true },
    { nome: 'Boquete (vilarejo cafeeiro)', wiki: 'Boquete, Chiriquí', cidade: 'Boquete', fora: true },
    { nome: 'Portobelo (forte colonial)', wiki: 'Portobelo, Colón', cidade: 'Portobelo', fora: true },
  ],
  PF: [
    { nome: 'Atol de Rangiroa', wiki: 'Rangiroa', cidade: 'Rangiroa', fora: true },
    { nome: 'Vale de Fatauiva (Hiva Oa)', wiki: 'Hiva Oa', cidade: 'Atuona', fora: true },
    { nome: 'Maupiti (irmã calma de Bora Bora)', wiki: 'Maupiti', cidade: 'Maupiti', fora: true },
    { nome: 'Atol de Fakarava (reserva da biosfera)', wiki: 'Fakarava', cidade: 'Fakarava', fora: true },
    { nome: 'Vale de Papenoo (Tahiti interior)', wiki: 'Papenoo', cidade: 'Papenoo', fora: true },
  ],
  PG: [
    { nome: 'Rio Sepik (vilarejos tribais)', wiki: 'Sepik River', cidade: 'Wewak', fora: true },
    { nome: 'Ilhas Trobriand', wiki: 'Trobriand Islands', cidade: 'Kiriwina', fora: true },
    { nome: 'Trilha Kokoda', wiki: 'Kokoda Track', cidade: 'Port Moresby', fora: true },
    { nome: 'Tufi (fiordes tropicais)', wiki: 'Tufi', cidade: 'Tufi', fora: true },
    { nome: 'Ilha Nova Bretanha (Rabaul)', wiki: 'Rabaul', cidade: 'Rabaul', fora: true },
  ],
  PH: [
    { nome: 'Terraços de arroz de Batad', wiki: 'Batad, Banaue', cidade: 'Banaue', fora: true },
    { nome: 'Ilha de Siquijor', wiki: 'Siquijor', cidade: 'Siquijor', fora: true },
    { nome: 'Vigan (cidade colonial)', wiki: 'Vigan', cidade: 'Ilocos Sur', fora: true },
    { nome: 'Ilhas Batanes', wiki: 'Batanes', cidade: 'Basco', fora: true },
    { nome: 'Rio subterrâneo de Puerto Princesa', wiki: 'Puerto Princesa Subterranean River National Park', cidade: 'Palawan', fora: true },
  ],
  PK: [
    { nome: 'Vale de Hunza', wiki: 'Hunza Valley', cidade: 'Karimabad', fora: true },
    { nome: 'Vale de Skardu (Baltistão)', wiki: 'Skardu', cidade: 'Skardu', fora: true },
    { nome: 'Forte de Derawar (deserto de Cholistan)', wiki: 'Derawar Fort', cidade: 'Bahawalpur', fora: true },
    { nome: 'Cidade antiga de Multan', wiki: 'Multan', cidade: 'Multan', fora: true },
    { nome: 'Vale de Kalash (Chitral)', wiki: 'Kalash Valleys', cidade: 'Chitral', fora: true },
  ],
  PL: [
    { nome: 'Cidade Velha de Toruń', wiki: 'Toruń', cidade: 'Toruń', fora: true },
    { nome: 'Parque Nacional de Białowieża', wiki: 'Białowieża National Park', cidade: 'Białowieża', fora: true },
    { nome: 'Minas de Sal de Bochnia', wiki: 'Bochnia Salt Mine', cidade: 'Bochnia', fora: true },
    { nome: 'Bairro Kazimierz (Cracóvia)', wiki: 'Kazimierz', cidade: 'Cracóvia', fora: true },
    { nome: 'Montanhas Bieszczady', wiki: 'Bieszczady Mountains', cidade: 'Ustrzyki Dolne', fora: true },
  ],
  PR: [
    { nome: 'Floresta de El Yunque', wiki: 'El Yunque National Forest', cidade: 'Río Grande', fora: true },
    { nome: 'Ilha de Culebra (Praia Flamenco)', wiki: 'Culebra, Puerto Rico', cidade: 'Culebra', fora: true },
    { nome: 'Cavernas do Río Camuy', wiki: 'Río Camuy Cave Park', cidade: 'Camuy', fora: true },
    { nome: 'Baía Bioluminescente de Vieques', wiki: 'Mosquito Bay', cidade: 'Vieques', fora: true },
    { nome: 'Ponce (cidade histórica)', wiki: 'Ponce, Puerto Rico', cidade: 'Ponce', fora: true },
  ],
  PS: [
    { nome: 'Sebastia (sítio arqueológico)', wiki: 'Sebastia, Nablus', cidade: 'Nablus', fora: true },
    { nome: 'Hisham\'s Palace', wiki: 'Hisham\'s Palace', cidade: 'Jericó', fora: true },
    { nome: 'Monte Gerizim', wiki: 'Mount Gerizim', cidade: 'Nablus', fora: true },
    { nome: 'Mosteiro de São Jorge de Choziba', wiki: 'Monastery of Saint George of Choziba', cidade: 'Wadi Qelt', fora: true },
    { nome: 'Battir (terraços agrícolas)', wiki: 'Battir', cidade: 'Battir', fora: true },
  ],
  PW: [
    { nome: 'Lago das Águas-Vivas (Jellyfish Lake)', wiki: 'Jellyfish Lake', cidade: 'Koror', fora: true },
    { nome: 'Ilhas Rochosas (Rock Islands Southern Lagoon)', wiki: 'Rock Islands Southern Lagoon', cidade: 'Koror', fora: true },
    { nome: 'Estado de Ngardmau e suas cachoeiras', wiki: 'Ngardmau', cidade: 'Ngardmau', fora: true },
    { nome: 'Ilha de Peleliu (memorial da Segunda Guerra)', wiki: 'Peleliu', cidade: 'Peleliu', fora: true },
    { nome: 'Ilha de Babeldaob e monólitos de Badrulchau', wiki: 'Badrulchau', cidade: 'Ngarchelong', fora: true },
  ],
  PY: [
    { nome: 'Trinidad (ruínas jesuíticas)', wiki: 'La Santísima Trinidad de Paraná', cidade: 'Trinidad', fora: true },
    { nome: 'Areguá (vilarejo de cerâmica)', wiki: 'Areguá', cidade: 'Areguá', fora: true },
    { nome: 'Parque Nacional Ybycuí', wiki: 'Ybycuí National Park', cidade: 'Ybycuí', fora: true },
    { nome: 'Chaco paraguaio (Filadélfia menonita)', wiki: 'Filadelfia, Paraguay', cidade: 'Filadelfia', fora: true },
    { nome: 'Concepción (porto fluvial colonial)', wiki: 'Concepción, Paraguay', cidade: 'Concepción', fora: true },
  ],
  QA: [
    { nome: 'Forte Al Zubarah', wiki: 'Al Zubarah', cidade: 'Al Shamal', fora: true },
    { nome: 'Vila abandonada de Al Jumail', wiki: 'Al Jumail', cidade: 'Al Shamal', fora: true },
    { nome: 'Reserva Natural de Khor Al Adaid (Mar Interior)', wiki: 'Khawr al Udayd', cidade: 'Mesaieed', fora: true },
    { nome: 'Petróglifos de Jebel Jassassiyeh', wiki: 'Al Jassasiya', cidade: 'Al Khor', fora: true },
    { nome: 'Mercado de camelos de Al Shahaniya', wiki: 'Al Shahaniya', cidade: 'Al Shahaniya', fora: true },
  ],
  RO: [
    { nome: 'Vila pintada de Viscri', wiki: 'Viscri', cidade: 'Brașov', fora: true },
    { nome: 'Mosteiros pintados de Bucovina', wiki: 'Painted churches of Moldavia', cidade: 'Suceava', fora: true },
    { nome: 'Maramureș (vilarejos de madeira)', wiki: 'Wooden Churches of Maramureș', cidade: 'Sighetu Marmației', fora: true },
    { nome: 'Delta do Danúbio', wiki: 'Danube Delta', cidade: 'Tulcea', fora: true },
    { nome: 'Estrada Transfăgărășan', wiki: 'Transfăgărășan', cidade: 'Sibiu', fora: true },
  ],
  RS: [
    { nome: 'Parque Nacional Piatra Craiului', wiki: 'Piatra Craiului National Park', cidade: 'Brașov', fora: true },
    { nome: 'Vilarejo de Viscri', wiki: 'Viscri', cidade: 'Brașov', fora: true },
    { nome: 'Delta do Danúbio', wiki: 'Danube Delta', cidade: 'Tulcea', fora: true },
    { nome: 'Mocănița do Vale do Vaser', wiki: 'Vaser Valley', cidade: 'Maramureș', fora: true },
    { nome: 'Mosteiros pintados da Bucovina', wiki: 'Painted churches of northern Moldavia', cidade: 'Suceava', fora: true },
  ],
  RU: [
    { nome: 'Lago Baikal (Ilha Olkhon)', wiki: 'Olkhon', cidade: 'Irkutsk', fora: true },
    { nome: 'Vale dos Gêiseres (Kamchatka)', wiki: 'Valley of Geysers', cidade: 'Kamchatka', fora: true },
    { nome: 'Anel de Ouro - Suzdal', wiki: 'Suzdal', cidade: 'Suzdal', fora: true },
    { nome: 'República de Tuva (Kyzyl)', wiki: 'Kyzyl', cidade: 'Kyzyl', fora: true },
    { nome: 'Parque Nacional Lena Pillars', wiki: 'Lena Pillars', cidade: 'Yakutsk', fora: true },
  ],
  RW: [
    { nome: 'Lago Kivu (Kibuye/Karongi)', wiki: 'Lake Kivu', cidade: 'Karongi', fora: true },
    { nome: 'Parque Nacional de Nyungwe', wiki: 'Nyungwe Forest National Park', cidade: 'Rusizi', fora: true },
    { nome: 'Parque Nacional Akagera', wiki: 'Akagera National Park', cidade: 'Kayonza', fora: true },
    { nome: 'Memorial do Genocídio de Murambi', wiki: 'Murambi Genocide Memorial Centre', cidade: 'Nyamagabe', fora: true },
    { nome: 'Vila Cultural Iby\'Iwacu', wiki: 'Iby\'Iwacu Cultural Village', cidade: 'Musanze', fora: true },
  ],
  SA: [
    { nome: 'Cidade histórica de Al-Ula', wiki: 'AlUla', cidade: 'Al-Ula', fora: true },
    { nome: 'Vilarejo de Rijal Almaa', wiki: 'Rijal Almaa', cidade: 'Asir', fora: true },
    { nome: 'Ilhas Farasan', wiki: 'Farasan Islands', cidade: 'Jazan', fora: true },
    { nome: 'Oásis de Al-Ahsa', wiki: 'Al-Ahsa Oasis', cidade: 'Hofuf', fora: true },
    { nome: 'Parque Nacional Asir', wiki: 'Asir National Park', cidade: 'Abha', fora: true },
  ],
  SB: [
    { nome: 'Lagoa de Marovo (maior lagoa de barreira dupla)', wiki: 'Marovo Lagoon', cidade: 'Província Ocidental', fora: true },
    { nome: 'Ilha de Tetepare (reserva comunitária)', wiki: 'Tetepare Island', cidade: 'Província Ocidental', fora: true },
    { nome: 'Ilha de Rennell (Lago Tegano, Patrimônio UNESCO)', wiki: 'Rennell Island', cidade: 'Rennell e Bellona', fora: true },
    { nome: 'Ilha de Kolombangara (vulcão e floresta tropical)', wiki: 'Kolombangara', cidade: 'Província Ocidental', fora: true },
    { nome: 'Ilha de Malaita (vila lacustre de Langa Langa)', wiki: 'Langa Langa Lagoon', cidade: 'Auki', fora: true },
  ],
  SC: [
    { nome: 'Ilha La Digue', wiki: 'La Digue', cidade: 'La Passe', fora: true },
    { nome: 'Reserva Natural Vallée de Mai', wiki: 'Vallée de Mai Nature Reserve', cidade: 'Praslin', fora: true },
    { nome: 'Atol de Aldabra', wiki: 'Aldabra', cidade: 'Aldabra', fora: true },
    { nome: 'Ilha Curieuse', wiki: 'Curieuse', cidade: 'Curieuse', fora: true },
    { nome: 'Mercado Sir Selwyn Selwyn-Clarke', wiki: 'Sir Selwyn Selwyn-Clarke Market', cidade: 'Victoria', fora: true },
  ],
  SD: [
    { nome: 'Pirâmides de Meroe', wiki: 'Mero%C3%AB', cidade: 'Shendi', fora: true },
    { nome: 'Jebel Barkal', wiki: 'Jebel_Barkal', cidade: 'Karima', fora: true },
    { nome: 'Ilha de Suakin', wiki: 'Suakin', cidade: 'Suakin', fora: true },
    { nome: 'Parque Nacional Dinder', wiki: 'Dinder_National_Park', cidade: 'Sennar', fora: true },
    { nome: 'Sítio arqueológico de Naqa', wiki: 'Naqa', cidade: 'Shendi', fora: true },
  ],
  SE: [
    { nome: 'Arquipélago de Göteborg', wiki: 'Gothenburg archipelago', cidade: 'Gotemburgo', fora: true },
    { nome: 'Parque Nacional Sarek', wiki: 'Sarek National Park', cidade: 'Jokkmokk', fora: true },
    { nome: 'Ilha de Gotland (Visby medieval)', wiki: 'Visby', cidade: 'Gotland', fora: true },
    { nome: 'Reserva natural de Höga Kusten', wiki: 'High Coast', cidade: 'Härnösand', fora: true },
    { nome: 'Vilarejo sami de Jukkasjärvi', wiki: 'Jukkasjärvi', cidade: 'Kiruna', fora: true },
  ],
  SG: [
    { nome: 'Bairro de Tiong Bahru', wiki: 'Tiong Bahru', cidade: 'Singapura', fora: true },
    { nome: 'Ilha de Pulau Ubin', wiki: 'Pulau Ubin', cidade: 'Singapura', fora: true },
    { nome: 'Reserva Natural de Bukit Timah', wiki: 'Bukit Timah Nature Reserve', cidade: 'Singapura', fora: true },
    { nome: 'Haw Par Villa', wiki: 'Haw Par Villa', cidade: 'Singapura', fora: true },
    { nome: 'Reserva de Sungei Buloh', wiki: 'Sungei Buloh Wetland Reserve', cidade: 'Singapura', fora: true },
  ],
  SI: [
    { nome: 'Vale do Logar (Logarska Dolina)', wiki: 'Logar Valley', cidade: 'Solčava', fora: true },
    { nome: 'Cavernas de Škocjan (UNESCO)', wiki: 'Škocjan Caves', cidade: 'Divača', fora: true },
    { nome: 'Vilarejo alpino de Velika Planina', wiki: 'Velika Planina', cidade: 'Kamnik', fora: true },
    { nome: 'Cidade medieval de Ptuj', wiki: 'Ptuj', cidade: 'Ptuj', fora: true },
    { nome: 'Vale do Soča (rio esmeralda)', wiki: 'Soča', cidade: 'Bovec', fora: true },
  ],
  SK: [
    { nome: 'Vilarejo de Vlkolínec (UNESCO)', wiki: 'Vlkolínec', cidade: 'Ružomberok', fora: true },
    { nome: 'Cidade mineira de Banská Štiavnica', wiki: 'Banská Štiavnica', cidade: 'Banská Štiavnica', fora: true },
    { nome: 'Parque Nacional do Paraíso Eslovaco', wiki: 'Slovak Paradise National Park', cidade: 'Spišská Nová Ves', fora: true },
    { nome: 'Caverna de Gelo de Dobšiná', wiki: 'Dobšiná Ice Cave', cidade: 'Dobšiná', fora: true },
    { nome: 'Castelo de Spiš', wiki: 'Spiš Castle', cidade: 'Spišské Podhradie', fora: true },
  ],
  SL: [
    { nome: 'Ilhas Banana', wiki: 'Banana Islands', cidade: 'Western Area Rural', fora: true },
    { nome: 'Reserva de Tiwai', wiki: 'Tiwai Island Wildlife Sanctuary', cidade: 'Pujehun', fora: true },
    { nome: 'Parque Nacional Outamba-Kilimi', wiki: 'Outamba-Kilimi National Park', cidade: 'Bombali', fora: true },
    { nome: 'Bunce Island', wiki: 'Bunce Island', cidade: 'Freetown', fora: true },
    { nome: 'Tacugama Chimpanzee Sanctuary', wiki: 'Tacugama Chimpanzee Sanctuary', cidade: 'Freetown', fora: true },
  ],
  SM: [
    { nome: 'Castelo de Montale', wiki: 'Montale (San Marino)', cidade: 'San Marino', fora: true },
    { nome: 'Vila de Borgo Maggiore', wiki: 'Borgo Maggiore', cidade: 'Borgo Maggiore', fora: true },
    { nome: 'Museu de Curiosidades', wiki: 'Museum of Curiosities', cidade: 'San Marino', fora: true },
    { nome: 'Cidade de Serravalle', wiki: 'Serravalle (San Marino)', cidade: 'Serravalle', fora: true },
    { nome: 'Castello di Fiorentino', wiki: 'Fiorentino', cidade: 'Fiorentino', fora: true },
  ],
  SN: [
    { nome: 'Ilha de Carabane', wiki: 'Carabane', cidade: 'Casamance', fora: true },
    { nome: 'Parque Nacional Niokolo-Koba', wiki: 'Niokolo-Koba National Park', cidade: 'Tambacounda', fora: true },
    { nome: 'Reserva de Bandia', wiki: 'Bandia Reserve', cidade: 'Thiès', fora: true },
    { nome: 'Lago Retba (Lac Rose)', wiki: 'Lake Retba', cidade: 'Dakar', fora: true },
    { nome: 'Delta do Saloum', wiki: 'Saloum Delta', cidade: 'Fatick', fora: true },
  ],
  SO: [
    { nome: 'Praias de Berbera', wiki: 'Berbera', cidade: 'Berbera', fora: true },
    { nome: 'Pinturas rupestres de Laas Geel', wiki: 'Laas Geel', cidade: 'Hargeisa', fora: true },
    { nome: 'Cidade antiga de Zeila', wiki: 'Zeila', cidade: 'Zeila', fora: true },
    { nome: 'Montanhas de Cal Madow', wiki: 'Cal Madow', cidade: 'Erigavo', fora: true },
    { nome: 'Ilha de Saad ad-Din', wiki: 'Saad ad-Din Island', cidade: 'Zeila', fora: true },
  ],
  SR: [
    { nome: 'Reserva Natural Central do Suriname', wiki: 'Central Suriname Nature Reserve', cidade: 'Sipaliwini', fora: true },
    { nome: 'Plantação Frederiksdorp', wiki: 'Frederiksdorp', cidade: 'Commewijne', fora: true },
    { nome: 'Reserva Natural de Galibi', wiki: 'Galibi Nature Reserve', cidade: 'Galibi', fora: true },
    { nome: 'Reserva Natural Brownsberg', wiki: 'Brownsberg Nature Park', cidade: 'Brokopondo', fora: true },
    { nome: 'Forte Nieuw Amsterdam', wiki: 'Fort Nieuw-Amsterdam', cidade: 'Nieuw Amsterdam', fora: true },
  ],
  SS: [
    { nome: 'Parque Nacional Boma', wiki: 'Boma National Park', cidade: 'Jonglei', fora: true },
    { nome: 'Parque Nacional Bandingilo', wiki: 'Bandingilo National Park', cidade: 'Equatória Central', fora: true },
    { nome: 'Cataratas de Fula', wiki: 'Fula Falls', cidade: 'Nimule', fora: true },
    { nome: 'Parque Nacional Nimule', wiki: 'Nimule National Park', cidade: 'Nimule', fora: true },
    { nome: 'Monte Kinyeti', wiki: 'Mount Kinyeti', cidade: 'Equatória Oriental', fora: true },
  ],
  ST: [
    { nome: 'Roça Água Izé', wiki: 'Água Izé', cidade: 'Cantagalo', fora: true },
    { nome: 'Lagoa Azul', wiki: 'Lagoa Azul (São Tomé e Príncipe)', cidade: 'Lobata', fora: true },
    { nome: 'Praia Jalé', wiki: 'Praia Jalé', cidade: 'Caué', fora: true },
    { nome: 'Roça Sundy', wiki: 'Roça Sundy', cidade: 'Pagué', fora: true },
    { nome: 'Cascata São Nicolau', wiki: 'Cascata de São Nicolau', cidade: 'Mé-Zóchi', fora: true },
  ],
  SV: [
    { nome: 'Ruta de las Flores', wiki: 'Ruta de las Flores', cidade: 'Ahuachapán', fora: true },
    { nome: 'Sítio arqueológico Joya de Cerén', wiki: 'Joya de Cerén', cidade: 'San Juan Opico', fora: true },
    { nome: 'Lago de Coatepeque', wiki: 'Lake Coatepeque', cidade: 'Santa Ana', fora: true },
    { nome: 'Suchitoto (cidade colonial)', wiki: 'Suchitoto', cidade: 'Suchitoto', fora: true },
    { nome: 'Parque Nacional El Imposible', wiki: 'El Imposible', cidade: 'Ahuachapán', fora: true },
  ],
  SY: [
    { nome: 'Cidade Antiga de Bosra', wiki: 'Bosra', cidade: 'Bosra', fora: true },
    { nome: 'Cidades Mortas (Aldeias Antigas do Norte da Síria)', wiki: 'Dead_Cities', cidade: 'Idlib', fora: true },
    { nome: 'Castelo Krak dos Cavaleiros', wiki: 'Krak_des_Chevaliers', cidade: 'Homs', fora: true },
    { nome: 'Maaloula (vilarejo aramaico)', wiki: 'Maaloula', cidade: 'Maaloula', fora: true },
    { nome: 'Apameia (sítio greco-romano)', wiki: 'Apamea,_Syria', cidade: 'Hama', fora: true },
  ],
  SZ: [
    { nome: 'Reserva Natural de Malolotja', wiki: 'Malolotja Nature Reserve', cidade: 'Hhohho', fora: true },
    { nome: 'Vale de Ezulwini (artesanato local)', wiki: 'Ezulwini Valley', cidade: 'Ezulwini', fora: true },
    { nome: 'Santuário de Vida Selvagem de Mlilwane', wiki: 'Mlilwane Wildlife Sanctuary', cidade: 'Lobamba', fora: true },
    { nome: 'Mercado de artesanato de Manzini', wiki: 'Manzini', cidade: 'Manzini', fora: true },
    { nome: 'Reserva de Caça de Mkhaya (rinocerontes)', wiki: 'Mkhaya Game Reserve', cidade: 'Siphofaneni', fora: true },
  ],
  TD: [
    { nome: 'Parque Nacional de Zakouma', wiki: 'Zakouma National Park', cidade: 'Am Timan', fora: true },
    { nome: 'Maciço de Ennedi', wiki: 'Ennedi Plateau', cidade: 'Fada', fora: true },
    { nome: 'Lagos de Ounianga', wiki: 'Lakes of Ounianga', cidade: 'Ounianga Kébir', fora: true },
    { nome: 'Reserva de Aouk-Aoukalé', wiki: 'Aouk Faunal Reserve', cidade: 'Sarh', fora: true },
    { nome: 'Cidade de Abéché', wiki: 'Abéché', cidade: 'Abéché', fora: true },
  ],
  TG: [
    { nome: 'Aldeia Tata Somba de Koutammakou', wiki: 'Koutammakou', cidade: 'Kara', fora: true },
    { nome: 'Cachoeiras de Kpalimé (Kpime)', wiki: 'Kpalimé', cidade: 'Kpalimé', fora: true },
    { nome: 'Parque Nacional Fazao-Malfakassa', wiki: 'Fazao Malfakassa National Park', cidade: 'Sokodé', fora: true },
    { nome: 'Aldeia lacustre de Togoville', wiki: 'Togoville', cidade: 'Togoville', fora: true },
    { nome: 'Monte Agou', wiki: 'Mount Agou', cidade: 'Kpalimé', fora: true },
  ],
  TJ: [
    { nome: 'Lagos de Iskanderkul', wiki: 'Iskanderkul', cidade: 'Sughd', fora: true },
    { nome: 'Vale de Wakhan (Pamir)', wiki: 'Wakhan Corridor', cidade: 'Khorog', fora: true },
    { nome: 'Lagos de Marguzor (Seven Lakes)', wiki: 'Haft Kul', cidade: 'Penjikent', fora: true },
    { nome: 'Sítio arqueológico de Sarazm', wiki: 'Sarazm', cidade: 'Penjikent', fora: true },
    { nome: 'Fortaleza de Hisor', wiki: 'Hissar Fortress', cidade: 'Hisor', fora: true },
  ],
  TL: [
    { nome: 'Ilha de Atauro', wiki: 'Atauro_Island', cidade: 'Atauro', fora: true },
    { nome: 'Parque Nacional Nino Konis Santana', wiki: 'Nino_Konis_Santana_National_Park', cidade: 'Lautém', fora: true },
    { nome: 'Monte Ramelau', wiki: 'Mount_Ramelau', cidade: 'Hatô-Builico', fora: true },
    { nome: 'Jaco Island', wiki: 'Jaco_Island', cidade: 'Tutuala', fora: true },
    { nome: 'Vila colonial de Maubisse', wiki: 'Maubisse', cidade: 'Maubisse', fora: true },
  ],
  TM: [
    { nome: 'Cratera de gás de Darvaza', wiki: 'Darvaza gas crater', cidade: 'Derweze', fora: true },
    { nome: 'Ruínas de Merv', wiki: 'Merv', cidade: 'Mary', fora: true },
    { nome: 'Konye-Urgench', wiki: 'Konye-Urgench', cidade: 'Konye-Urgench', fora: true },
    { nome: 'Parque Nacional de Köýtendag', wiki: 'Koytendag Nature Reserve', cidade: 'Köýtendag', fora: true },
    { nome: 'Cânion de Yangykala', wiki: 'Yangykala Canyon', cidade: 'Balkan', fora: true },
  ],
  TN: [
    { nome: 'Ilha de Djerba', wiki: 'Djerba', cidade: 'Djerba', fora: true },
    { nome: 'Vilarejo berbere de Chenini', wiki: 'Chenini', cidade: 'Tataouine', fora: true },
    { nome: 'Oásis de montanha de Chebika', wiki: 'Chebika', cidade: 'Tozeur', fora: true },
    { nome: 'Anfiteatro de El Djem', wiki: 'Amphitheatre of El Jem', cidade: 'El Djem', fora: true },
    { nome: 'Parque Nacional de Ichkeul', wiki: 'Ichkeul National Park', cidade: 'Bizerte', fora: true },
  ],
  TO: [
    { nome: 'Ilhas Vava\'u', wiki: 'Vavaʻu', cidade: 'Neiafu', fora: true },
    { nome: 'Grupo de Ilhas Ha\'apai', wiki: 'Haʻapai', cidade: 'Pangai', fora: true },
    { nome: 'Ilha de \'Eua', wiki: 'ʻEua', cidade: 'ʻOhonua', fora: true },
    { nome: 'Blowholes de Mapu\'a \'a Vaca', wiki: 'Mapuʻa ʻa Vaea', cidade: 'Houma', fora: true },
    { nome: 'Trilithon Ha\'amonga \'a Maui', wiki: 'Haʻamonga ʻa Maui', cidade: 'Niutōua', fora: true },
  ],
  TT: [
    { nome: 'Centro de Vida Selvagem Asa Wright', wiki: 'Asa Wright Nature Centre', cidade: 'Arima', fora: true },
    { nome: 'Praia de Maracas', wiki: 'Maracas Bay', cidade: 'Maracas', fora: true },
    { nome: 'Pântano de Caroni', wiki: 'Caroni Swamp', cidade: 'Caroni', fora: true },
    { nome: 'Vilarejo de Charlotteville', wiki: 'Charlotteville', cidade: 'Charlotteville', fora: true },
    { nome: 'Reserva Florestal de Main Ridge', wiki: 'Main Ridge Forest Reserve', cidade: 'Tobago', fora: true },
  ],
  TV: [
    { nome: 'Atol de Funafuti (Área de Conservação)', wiki: 'Funafuti_Conservation_Area', cidade: 'Funafuti', fora: true },
    { nome: 'Ilhota de Nanumea', wiki: 'Nanumea', cidade: 'Nanumea', fora: true },
    { nome: 'Atol de Nukufetau', wiki: 'Nukufetau', cidade: 'Nukufetau', fora: true },
    { nome: 'Ilha de Vaitupu', wiki: 'Vaitupu', cidade: 'Vaitupu', fora: true },
    { nome: 'Atol de Nui', wiki: 'Nui_(atoll)', cidade: 'Nui', fora: true },
  ],
  TW: [
    { nome: 'Vilarejo de Jiufen', wiki: 'Jiufen', cidade: 'Ruifang', fora: true },
    { nome: 'Garganta de Taroko', wiki: 'Taroko National Park', cidade: 'Hualien', fora: true },
    { nome: 'Ilha Verde (Lyudao)', wiki: 'Green Island, Taiwan', cidade: 'Taitung', fora: true },
    { nome: 'Floresta Recreativa de Alishan', wiki: 'Alishan National Scenic Area', cidade: 'Chiayi', fora: true },
    { nome: 'Lago do Sol e da Lua', wiki: 'Sun Moon Lake', cidade: 'Nantou', fora: true },
  ],
  TZ: [
    { nome: 'Parque Nacional de Mahale Mountains', wiki: 'Mahale Mountains National Park', cidade: 'Kigoma', fora: true },
    { nome: 'Reserva de Selous (Nyerere)', wiki: 'Nyerere National Park', cidade: 'Morogoro', fora: true },
    { nome: 'Ilha de Mafia', wiki: 'Mafia Island', cidade: 'Mafia', fora: true },
    { nome: 'Montes Usambara', wiki: 'Usambara Mountains', cidade: 'Lushoto', fora: true },
    { nome: 'Parque Nacional Katavi', wiki: 'Katavi National Park', cidade: 'Mpanda', fora: true },
  ],
  UA: [
    { nome: 'Cidade subterrânea de Kamianets-Podilskyi', wiki: 'Kamianets-Podilskyi', cidade: 'Kamianets-Podilskyi', fora: true },
    { nome: 'Túnel do Amor em Klevan', wiki: 'Tunnel of Love (Ukraine)', cidade: 'Klevan', fora: true },
    { nome: 'Montanhas dos Cárpatos ucranianos', wiki: 'Ukrainian Carpathians', cidade: 'Ivano-Frankivsk', fora: true },
    { nome: 'Cidade velha de Lviv', wiki: 'Lviv', cidade: 'Lviv', fora: true },
    { nome: 'Reserva da Biosfera do Danúbio', wiki: 'Danube Biosphere Reserve', cidade: 'Vylkove', fora: true },
  ],
  UG: [
    { nome: 'Parque Nacional Kidepo Valley', wiki: 'Kidepo Valley National Park', cidade: 'Karenga', fora: true },
    { nome: 'Ilhas Ssese no Lago Vitória', wiki: 'Ssese Islands', cidade: 'Kalangala', fora: true },
    { nome: 'Parque Nacional do Monte Elgon', wiki: 'Mount Elgon National Park', cidade: 'Mbale', fora: true },
    { nome: 'Floresta de Kibale (chimpanzés)', wiki: 'Kibale National Park', cidade: 'Fort Portal', fora: true },
    { nome: 'Cachoeiras de Sipi', wiki: 'Sipi Falls', cidade: 'Kapchorwa', fora: true },
  ],
  UY: [
    { nome: 'Cabo Polonio (vila sem eletricidade)', wiki: 'Cabo Polonio', cidade: 'Rocha', fora: true },
    { nome: 'Termas del Daymán', wiki: 'Termas del Daymán', cidade: 'Salto', fora: true },
    { nome: 'Valle del Lunarejo', wiki: 'Valle del Lunarejo', cidade: 'Rivera', fora: true },
    { nome: 'Quebrada de los Cuervos', wiki: 'Quebrada de los Cuervos', cidade: 'Treinta y Tres', fora: true },
    { nome: 'Carmelo (vinícolas boutique)', wiki: 'Carmelo, Uruguay', cidade: 'Colonia', fora: true },
  ],
  UZ: [
    { nome: 'Cidade antiga de Termez', wiki: 'Termez', cidade: 'Termez', fora: true },
    { nome: 'Vale de Ferganá', wiki: 'Fergana Valley', cidade: 'Fergana', fora: true },
    { nome: 'Nukus e Museu Savitsky', wiki: 'Nukus Museum of Art', cidade: 'Nukus', fora: true },
    { nome: 'Shahrisabz (cidade natal de Tamerlão)', wiki: 'Shahrisabz', cidade: 'Shahrisabz', fora: true },
    { nome: 'Lago Aydar', wiki: 'Aydar Lake', cidade: 'Jizzakh', fora: true },
  ],
  VA: [
    { nome: 'Jardins do Vaticano', wiki: 'Vatican Gardens', cidade: 'Cidade do Vaticano', fora: true },
    { nome: 'Necrópole Vaticana (Scavi)', wiki: 'Vatican Necropolis', cidade: 'Cidade do Vaticano', fora: true },
    { nome: 'Biblioteca Apostólica Vaticana', wiki: 'Vatican Library', cidade: 'Cidade do Vaticano', fora: true },
    { nome: 'Museu Pio-Cristão', wiki: 'Pio Cristiano Museum', cidade: 'Cidade do Vaticano', fora: true },
    { nome: 'Estação Ferroviária do Vaticano', wiki: 'Vatican City railway station', cidade: 'Cidade do Vaticano', fora: true },
  ],
  VC: [
    { nome: 'Vulcão La Soufrière (trilha)', wiki: 'La Soufrière (Saint Vincent)', cidade: 'Chateaubelair', fora: true },
    { nome: 'Ilha de Bequia (vila Port Elizabeth)', wiki: 'Bequia', cidade: 'Port Elizabeth', fora: true },
    { nome: 'Tobago Cays Marine Park', wiki: 'Tobago Cays', cidade: 'Union Island', fora: true },
    { nome: 'Jardim Botânico de Kingstown', wiki: 'Kingstown Botanic Gardens', cidade: 'Kingstown', fora: true },
    { nome: 'Cataratas de Dark View', wiki: 'Dark View Falls', cidade: 'Chateaubelair', fora: true },
  ],
  VE: [
    { nome: 'Gran Sabana (tepuis)', wiki: 'Gran Sabana', cidade: 'Bolívar', fora: true },
    { nome: 'Parque Nacional Mochima', wiki: 'Mochima National Park', cidade: 'Anzoátegui', fora: true },
    { nome: 'Médanos de Coro', wiki: 'Médanos de Coro National Park', cidade: 'Coro', fora: true },
    { nome: 'Teleférico de Mérida', wiki: 'Mérida cable car', cidade: 'Mérida', fora: true },
    { nome: 'Los Roques (arquipélago)', wiki: 'Los Roques archipelago', cidade: 'Los Roques', fora: true },
  ],
  VU: [
    { nome: 'Vulcão Mount Yasur', wiki: 'Mount Yasur', cidade: 'Tanna', fora: true },
    { nome: 'Cachoeiras de Mele', wiki: 'Mele Cascades', cidade: 'Mele', fora: true },
    { nome: 'Ilha de Pentecost (salto Nagol)', wiki: 'Pentecost Island', cidade: 'Pentecost', fora: true },
    { nome: 'Champagne Beach', wiki: 'Champagne Beach', cidade: 'Espiritu Santo', fora: true },
    { nome: 'Buraco azul de Nanda', wiki: 'Espiritu Santo', cidade: 'Espiritu Santo', fora: true },
  ],
  WS: [
    { nome: 'Piscinas de To Sua', wiki: 'To Sua Ocean Trench', cidade: 'Lotofaga', fora: true },
    { nome: 'Cachoeiras de Papapapaitai', wiki: 'Papapapai-tai Falls', cidade: 'Siumu', fora: true },
    { nome: 'Reserva de Conservação O Le Pupu-Pue', wiki: 'O Le Pupu-Puʻe National Park', cidade: 'Upolu', fora: true },
    { nome: 'Vila de Lalomanu', wiki: 'Lalomanu', cidade: 'Aleipata', fora: true },
    { nome: 'Ilha de Manono', wiki: 'Manono Island', cidade: 'Aiga-i-le-Tai', fora: true },
  ],
  XK: [
    { nome: 'Cidade histórica de Prizren', wiki: 'Prizren', cidade: 'Prizren', fora: true },
    { nome: 'Parque Nacional de Sharr', wiki: 'Sharr Mountains National Park', cidade: 'Štrpce', fora: true },
    { nome: 'Cânion de Rugova', wiki: 'Rugova Canyon', cidade: 'Peja', fora: true },
    { nome: 'Mosteiro de Visoki Dečani', wiki: 'Visoki Dečani', cidade: 'Deçan', fora: true },
    { nome: 'Cidade de Gjakova (bazar antigo)', wiki: 'Gjakova', cidade: 'Gjakova', fora: true },
  ],
  YE: [
    { nome: 'Ilha de Socotra', wiki: 'Socotra', cidade: 'Hadibu', fora: true },
    { nome: 'Vila de Al Hajjarah', wiki: 'Al Hajjarah', cidade: 'Manakhah', fora: true },
    { nome: 'Wadi Dawan', wiki: 'Wadi Daw\'an', cidade: 'Hadramaute', fora: true },
    { nome: 'Cidade antiga de Zabid', wiki: 'Zabid', cidade: 'Zabid', fora: true },
    { nome: 'Cidade fortificada de Thula', wiki: 'Thula, Yemen', cidade: 'Thula', fora: true },
  ],
  ZM: [
    { nome: 'Parque Nacional Kafue', wiki: 'Kafue National Park', cidade: 'Mumbwa', fora: true },
    { nome: 'Quedas de Kalambo', wiki: 'Kalambo Falls', cidade: 'Mbala', fora: true },
    { nome: 'Parque Nacional Liuwa Plain', wiki: 'Liuwa Plain National Park', cidade: 'Kalabo', fora: true },
    { nome: 'Lago Bangweulu e seus pântanos', wiki: 'Lake Bangweulu', cidade: 'Samfya', fora: true },
    { nome: 'Cerimônia Kuomboka', wiki: 'Kuomboka', cidade: 'Mongu', fora: true },
  ],
  ZW: [
    { nome: 'Parque Nacional Mana Pools', wiki: 'Mana Pools National Park', cidade: 'Kariba', fora: true },
    { nome: 'Montes Chimanimani', wiki: 'Chimanimani Mountains', cidade: 'Chimanimani', fora: true },
    { nome: 'Parque Nacional Matobo', wiki: 'Matobo National Park', cidade: 'Bulawayo', fora: true },
    { nome: 'Ruínas de Khami', wiki: 'Khami', cidade: 'Bulawayo', fora: true },
    { nome: 'Vale do Save (Gonarezhou)', wiki: 'Gonarezhou National Park', cidade: 'Chiredzi', fora: true },
  ],
};
