// Pontos turísticos curados manualmente para os 38 países que ficaram FORA do
// JSON auto-gerado em atracoes.js. Mesma forma: {nome, wiki, cidade}.
// Mergeado em atracoesDoPais — código DESTE arquivo nunca é regerado por workflow.
//
// Critério de curadoria:
//   • 'wiki' é o título do artigo em pt.wikipedia.org. Quando o artigo só existe
//     em en, deixei o título em inglês (imagemWiki/resumoClient caem em en).
//   • Mínimo 6 pontos por país. Mais quando o país tem turismo real.
//   • Foco em sítios UNESCO, marcos naturais, e cidades históricas.
//
// Países instáveis (Iraque, Síria, Iêmen, Afeganistão, Sudão, RDC etc.): o app
// já mostra disclaimer "confira na fonte oficial" + alertas de segurança. O
// catálogo cobre a CULTURA do lugar, não recomenda visita imediata.

export const ATRACOES_EXTRA = {
  RU: [
    { nome: 'Praça Vermelha', wiki: 'Praça Vermelha', cidade: 'Moscou' },
    { nome: 'Kremlin de Moscou', wiki: 'Kremlin de Moscou', cidade: 'Moscou' },
    { nome: 'Catedral de São Basílio', wiki: 'Catedral de São Basílio', cidade: 'Moscou' },
    { nome: 'Museu Hermitage', wiki: 'Museu Hermitage', cidade: 'São Petersburgo' },
    { nome: 'Palácio de Inverno', wiki: 'Palácio de Inverno', cidade: 'São Petersburgo' },
    { nome: 'Igreja do Salvador sobre o Sangue Derramado', wiki: 'Igreja do Salvador sobre o Sangue Derramado', cidade: 'São Petersburgo' },
    { nome: 'Lago Baikal', wiki: 'Lago Baikal', cidade: 'Sibéria' },
    { nome: 'Transiberiana', wiki: 'Ferrovia Transiberiana', cidade: 'Moscou-Vladivostok' },
    { nome: 'Anel de Ouro da Rússia', wiki: 'Anel de Ouro da Rússia', cidade: 'Suzdal' },
    { nome: 'Mosteiro da Trindade-São Sérgio', wiki: 'Lavra da Trindade-São Sérgio', cidade: 'Sergiyev Posad' },
    { nome: 'Kazan Kremlin', wiki: 'Kremlin de Kazan', cidade: 'Kazan' },
    { nome: 'Vulcões de Kamchatka', wiki: 'Vulcões de Kamchatka', cidade: 'Kamchatka' },
  ],
  VA: [
    { nome: 'Basílica de São Pedro', wiki: 'Basílica de São Pedro', cidade: 'Cidade do Vaticano' },
    { nome: 'Praça de São Pedro', wiki: 'Praça de São Pedro', cidade: 'Cidade do Vaticano' },
    { nome: 'Capela Sistina', wiki: 'Capela Sistina', cidade: 'Cidade do Vaticano' },
    { nome: 'Museus Vaticanos', wiki: 'Museus Vaticanos', cidade: 'Cidade do Vaticano' },
    { nome: 'Jardins do Vaticano', wiki: 'Jardins do Vaticano', cidade: 'Cidade do Vaticano' },
    { nome: 'Necrópole Vaticana', wiki: 'Necrópole Vaticana', cidade: 'Cidade do Vaticano' },
    { nome: 'Biblioteca Apostólica Vaticana', wiki: 'Biblioteca Apostólica Vaticana', cidade: 'Cidade do Vaticano' },
    { nome: 'Arquivo Apostólico do Vaticano', wiki: 'Arquivo Apostólico do Vaticano', cidade: 'Cidade do Vaticano' },
  ],
  AF: [
    { nome: 'Vale de Bamiyan', wiki: 'Vale de Bamiyan', cidade: 'Bamiyan' },
    { nome: 'Cidadela de Herat', wiki: 'Cidadela de Herat', cidade: 'Herat' },
    { nome: 'Minarete de Jam', wiki: 'Minarete de Jam', cidade: 'Ghor' },
    { nome: 'Mesquita Azul de Mazar-i-Sharif', wiki: 'Santuário de Hazrat Ali', cidade: 'Mazar-i-Sharif' },
    { nome: 'Lagos de Band-e Amir', wiki: 'Band-e Amir', cidade: 'Bamiyan' },
    { nome: 'Jardim de Babur', wiki: 'Jardim de Babur', cidade: 'Cabul' },
    { nome: 'Museu Nacional do Afeganistão', wiki: 'Museu Nacional do Afeganistão', cidade: 'Cabul' },
  ],
  IQ: [
    { nome: 'Babilônia', wiki: 'Babilônia', cidade: 'Babil' },
    { nome: 'Cidade Antiga de Ur', wiki: 'Ur', cidade: 'Dhi Qar' },
    { nome: 'Hatra', wiki: 'Hatra', cidade: 'Nínive' },
    { nome: 'Samarra', wiki: 'Samarra', cidade: 'Saladino' },
    { nome: 'Mesquita do Imam Husayn', wiki: 'Santuário do Imam Hussain', cidade: 'Karbala' },
    { nome: 'Cidade Velha de Bagdá', wiki: 'Bagdá', cidade: 'Bagdá' },
    { nome: 'Erbil Citadel', wiki: 'Cidadela de Erbil', cidade: 'Erbil' },
    { nome: 'Pântanos da Mesopotâmia', wiki: 'Pântanos da Mesopotâmia', cidade: 'Sul do Iraque' },
  ],
  SY: [
    { nome: 'Palmira', wiki: 'Palmira', cidade: 'Tadmur' },
    { nome: 'Mesquita dos Omíadas', wiki: 'Mesquita dos Omíadas', cidade: 'Damasco' },
    { nome: 'Cidade Velha de Damasco', wiki: 'Damasco', cidade: 'Damasco' },
    { nome: 'Cidade Velha de Aleppo', wiki: 'Aleppo', cidade: 'Aleppo' },
    { nome: 'Krak des Chevaliers', wiki: 'Krak des Chevaliers', cidade: 'Homs' },
    { nome: 'Bosra', wiki: 'Bosra', cidade: 'Dara' },
    { nome: 'Cidades Mortas', wiki: 'Cidades mortas', cidade: 'Idlib' },
    { nome: 'Ugarit', wiki: 'Ugarit', cidade: 'Latakia' },
  ],
  LY: [
    { nome: 'Leptis Magna', wiki: 'Leptis Magna', cidade: 'Khoms' },
    { nome: 'Sabratha', wiki: 'Sabratha', cidade: 'Tripolitânia' },
    { nome: 'Cirene', wiki: 'Cirene', cidade: 'Cirenaica' },
    { nome: 'Ghadames', wiki: 'Ghadames', cidade: 'Tripolitânia' },
    { nome: 'Tadrart Acacus', wiki: 'Tadrart Acacus', cidade: 'Fezzan' },
    { nome: 'Medina de Trípoli', wiki: 'Trípoli', cidade: 'Trípoli' },
    { nome: 'Castelo Vermelho de Trípoli', wiki: 'Assai al-Hamra', cidade: 'Trípoli' },
  ],
  YE: [
    { nome: 'Cidade Velha de Sana', wiki: 'Sana', cidade: 'Sana' },
    { nome: 'Shibam', wiki: 'Shibam', cidade: 'Hadramaute' },
    { nome: 'Ilha de Socotra', wiki: 'Socotra', cidade: 'Socotra' },
    { nome: 'Zabid', wiki: 'Zabid', cidade: 'Hodeida' },
    { nome: 'Aden', wiki: 'Aden', cidade: 'Aden' },
    { nome: 'Marib', wiki: 'Marib', cidade: 'Marib' },
    { nome: 'Mocha', wiki: 'Mocha (Iêmen)', cidade: 'Mar Vermelho' },
  ],
  PS: [
    { nome: 'Basílica da Natividade', wiki: 'Basílica da Natividade', cidade: 'Belém' },
    { nome: 'Cidade Velha de Hebron', wiki: 'Hebron', cidade: 'Hebron' },
    { nome: 'Mosteiro de São Jorge de Coziba', wiki: 'Mosteiro de São Jorge de Coziba', cidade: 'Jericó' },
    { nome: 'Tell es-Sultan (Antiga Jericó)', wiki: 'Jericó', cidade: 'Jericó' },
    { nome: 'Túmulo dos Patriarcas', wiki: 'Caverna dos Patriarcas', cidade: 'Hebron' },
    { nome: 'Mar Morto (lado palestino)', wiki: 'Mar Morto', cidade: 'Vale do Jordão' },
    { nome: 'Cidade Velha de Nablus', wiki: 'Nablus', cidade: 'Nablus' },
  ],
  SD: [
    { nome: 'Pirâmides de Meroé', wiki: 'Meroé', cidade: 'Estado do Nilo' },
    { nome: 'Jebel Barkal', wiki: 'Jebel Barkal', cidade: 'Karima' },
    { nome: 'Suakin', wiki: 'Suakin', cidade: 'Mar Vermelho' },
    { nome: 'Naqa', wiki: 'Naqa', cidade: 'Khartum do Norte' },
    { nome: 'Confluência dos Nilos', wiki: 'Cartum', cidade: 'Cartum' },
    { nome: 'Parque Nacional de Dinder', wiki: 'Parque Nacional Dinder', cidade: 'Sennar' },
    { nome: 'Old Dongola', wiki: 'Antiga Dongola', cidade: 'Estado do Norte' },
  ],
  SS: [
    { nome: 'Parque Nacional Boma', wiki: 'Parque Nacional Boma', cidade: 'Jonglei' },
    { nome: 'Cataratas do Nilo Branco', wiki: 'Nilo Branco', cidade: 'Equatória Central' },
    { nome: 'Parque Nacional Sudd', wiki: 'Sudd', cidade: 'Centro-norte' },
    { nome: 'Juba', wiki: 'Juba', cidade: 'Juba' },
    { nome: 'Reserva de Caça Bandingilo', wiki: 'Parque Nacional Bandingilo', cidade: 'Equatória Oriental' },
    { nome: 'Catedral de Santa Teresa de Juba', wiki: 'Juba', cidade: 'Juba' },
    { nome: 'Rio Nilo no Sudão do Sul', wiki: 'Rio Nilo', cidade: 'Juba' },
  ],
  KP: [
    { nome: 'Praça Kim Il-sung', wiki: 'Praça Kim Il-sung', cidade: 'Pyongyang' },
    { nome: 'Arco do Triunfo de Pyongyang', wiki: 'Arco do Triunfo (Coreia do Norte)', cidade: 'Pyongyang' },
    { nome: 'Monumento Mansudae', wiki: 'Grande Monumento Mansudae', cidade: 'Pyongyang' },
    { nome: 'Torre Juche', wiki: 'Torre Juche', cidade: 'Pyongyang' },
    { nome: 'Zona Desmilitarizada (DMZ)', wiki: 'Zona desmilitarizada da Coreia', cidade: 'Panmunjom' },
    { nome: 'Monte Paektu', wiki: 'Monte Baekdu', cidade: 'Ryanggang' },
    { nome: 'Monte Kumgang', wiki: 'Monte Kumgang', cidade: 'Kangwon' },
    { nome: 'Tumbas Reais da Dinastia Koryo', wiki: 'Túmulos da dinastia Koryo', cidade: 'Kaesong' },
  ],
  TL: [
    { nome: 'Cristo Rei de Díli', wiki: 'Cristo Rei de Díli', cidade: 'Díli' },
    { nome: 'Ilha de Ataúro', wiki: 'Ataúro', cidade: 'Ataúro' },
    { nome: 'Ilha de Jaco', wiki: 'Ilha de Jaco', cidade: 'Lautém' },
    { nome: 'Parque Nacional Nino Konis Santana', wiki: 'Parque Nacional Nino Konis Santana', cidade: 'Lautém' },
    { nome: 'Maubisse', wiki: 'Maubisse', cidade: 'Ainaro' },
    { nome: 'Mercado de Tais', wiki: 'Tais', cidade: 'Díli' },
    { nome: 'Praia de Areia Branca', wiki: 'Díli', cidade: 'Díli' },
  ],
  ML: [
    { nome: 'Timbuktu', wiki: 'Tombuctu', cidade: 'Tombuctu' },
    { nome: 'Djenné', wiki: 'Djenné', cidade: 'Mopti' },
    { nome: 'Grande Mesquita de Djenné', wiki: 'Grande Mesquita de Djenné', cidade: 'Djenné' },
    { nome: 'Falésia de Bandiagara', wiki: 'Falésia de Bandiagara', cidade: 'Mopti' },
    { nome: 'Túmulo dos Askia', wiki: 'Tumba dos Askia', cidade: 'Gao' },
    { nome: 'Rio Níger em Mopti', wiki: 'Mopti', cidade: 'Mopti' },
    { nome: 'Bamako', wiki: 'Bamako', cidade: 'Bamako' },
  ],
  MR: [
    { nome: 'Banc d\'Arguin', wiki: 'Parque Nacional do Banco de Arguim', cidade: 'Costa Atlântica' },
    { nome: 'Chinguetti', wiki: 'Chinguetti', cidade: 'Adrar' },
    { nome: 'Ouadane', wiki: 'Ouadane', cidade: 'Adrar' },
    { nome: 'Tichitt', wiki: 'Tichitt', cidade: 'Tagant' },
    { nome: 'Oualata', wiki: 'Oualata', cidade: 'Hodh Ech Chargui' },
    { nome: 'Olho do Saara (Estrutura Richat)', wiki: 'Estrutura Richat', cidade: 'Ouadane' },
    { nome: 'Nouakchott', wiki: 'Nuaquechote', cidade: 'Nouakchott' },
    { nome: 'Trem do Minério', wiki: 'Ferrovia da Mauritânia', cidade: 'Nouadhibou-Zouérat' },
  ],
  BF: [
    { nome: 'Ruínas de Loropéni', wiki: 'Ruínas de Loropéni', cidade: 'Sudoeste' },
    { nome: 'Grande Mesquita de Bobo-Dioulasso', wiki: 'Grande Mesquita de Bobo-Dioulasso', cidade: 'Bobo-Dioulasso' },
    { nome: 'Reserva de Nazinga', wiki: 'Reserva de Nazinga', cidade: 'Centro-Sul' },
    { nome: 'Sindou Peaks', wiki: 'Picos de Sindou', cidade: 'Sindou' },
    { nome: 'Banfora', wiki: 'Banfora', cidade: 'Cascades' },
    { nome: 'Cascatas de Karfiguéla', wiki: 'Cascatas de Karfiguéla', cidade: 'Banfora' },
    { nome: 'Ouagadougou', wiki: 'Uagadugu', cidade: 'Ouagadougou' },
  ],
  NE: [
    { nome: 'Reserva de Aïr e Ténéré', wiki: 'Reservas Naturais do Aïr e Teneré', cidade: 'Agadez' },
    { nome: 'Cidade Velha de Agadez', wiki: 'Agadez', cidade: 'Agadez' },
    { nome: 'Parque Nacional W', wiki: 'Parque Nacional do W', cidade: 'Tillabéri' },
    { nome: 'Vale do Termit', wiki: 'Maciço de Termit', cidade: 'Zinder' },
    { nome: 'Niamey', wiki: 'Niamey', cidade: 'Niamey' },
    { nome: 'Girafas de Kouré', wiki: 'Girafa-do-norte', cidade: 'Tillabéri' },
  ],
  TD: [
    { nome: 'Lagos de Ounianga', wiki: 'Lagos de Ounianga', cidade: 'Ennedi' },
    { nome: 'Maciço de Ennedi', wiki: 'Maciço de Ennedi', cidade: 'Ennedi' },
    { nome: 'Parque Nacional Zakouma', wiki: 'Parque Nacional Zakouma', cidade: 'Salamat' },
    { nome: 'Lago Chade', wiki: 'Lago Chade', cidade: 'Oeste' },
    { nome: 'N\'Djamena', wiki: 'N\'Djamena', cidade: 'N\'Djamena' },
    { nome: 'Sahara Chadiano', wiki: 'Tibesti', cidade: 'Tibesti' },
  ],
  CF: [
    { nome: 'Parque Nacional de Manovo-Gounda St Floris', wiki: 'Parque Nacional Manovo-Gounda St. Floris', cidade: 'Bamingui-Bangoran' },
    { nome: 'Reserva Especial de Dzanga-Sangha', wiki: 'Reserva Especial Dzanga-Sangha', cidade: 'Sangha-Mbaéré' },
    { nome: 'Bangui', wiki: 'Bangui', cidade: 'Bangui' },
    { nome: 'Catedral de Notre-Dame de Bangui', wiki: 'Catedral de Notre-Dame de Bangui', cidade: 'Bangui' },
    { nome: 'Rio Oubangui', wiki: 'Rio Ubangui', cidade: 'Bangui' },
    { nome: 'Cataratas Boali', wiki: 'Cataratas Boali', cidade: 'Ombella-Mpoko' },
    { nome: 'Floresta de Ngotto', wiki: 'Floresta de Ngotto', cidade: 'Lobaye' },
  ],
  CD: [
    { nome: 'Parque Nacional de Virunga', wiki: 'Parque Nacional de Virunga', cidade: 'Kivu do Norte' },
    { nome: 'Vulcão Nyiragongo', wiki: 'Nyiragongo', cidade: 'Goma' },
    { nome: 'Parque Nacional Garamba', wiki: 'Parque Nacional Garamba', cidade: 'Haut-Uélé' },
    { nome: 'Parque Nacional de Kahuzi-Biéga', wiki: 'Parque Nacional de Kahuzi-Biega', cidade: 'Kivu do Sul' },
    { nome: 'Parque Nacional Salonga', wiki: 'Parque Nacional Salonga', cidade: 'Centro' },
    { nome: 'Reserva de Vida Selvagem de Okapi', wiki: 'Reserva da Fauna do Okapi', cidade: 'Ituri' },
    { nome: 'Kinshasa', wiki: 'Quinxassa', cidade: 'Kinshasa' },
    { nome: 'Rio Congo', wiki: 'Rio Congo', cidade: 'Kinshasa-Brazzaville' },
  ],
  CG: [
    { nome: 'Parque Nacional Odzala-Kokoua', wiki: 'Parque Nacional Odzala', cidade: 'Cuvette-Ouest' },
    { nome: 'Parque Nacional Nouabalé-Ndoki', wiki: 'Parque Nacional Nouabalé-Ndoki', cidade: 'Sangha' },
    { nome: 'Brazzaville', wiki: 'Brazavile', cidade: 'Brazzaville' },
    { nome: 'Basílica de Santa Ana', wiki: 'Brazavile', cidade: 'Brazzaville' },
    { nome: 'Cataratas Loufoulakari', wiki: 'Rio Congo', cidade: 'Pool' },
    { nome: 'Ilhas Loango', wiki: 'Reino do Loango', cidade: 'Costa Atlântica' },
  ],
  GQ: [
    { nome: 'Malabo', wiki: 'Malabo', cidade: 'Bioko' },
    { nome: 'Ilha de Bioko', wiki: 'Bioko', cidade: 'Bioko' },
    { nome: 'Vulcão Pico Basile', wiki: 'Pico Basile', cidade: 'Bioko' },
    { nome: 'Reserva Natural Monte Alén', wiki: 'Parque Nacional Monte Alén', cidade: 'Litoral' },
    { nome: 'Bata', wiki: 'Bata (cidade)', cidade: 'Bata' },
    { nome: 'Ilha de Annobón', wiki: 'Ano Bom', cidade: 'Annobón' },
  ],
  ER: [
    { nome: 'Asmara', wiki: 'Asmara', cidade: 'Asmara' },
    { nome: 'Massawa', wiki: 'Massawa', cidade: 'Mar Vermelho do Norte' },
    { nome: 'Ilhas Dahlak', wiki: 'Arquipélago de Dahlak', cidade: 'Mar Vermelho' },
    { nome: 'Qohaito', wiki: 'Qohaito', cidade: 'Debub' },
    { nome: 'Adulis', wiki: 'Adulis', cidade: 'Massawa' },
    { nome: 'Catedral Católica de Asmara', wiki: 'Asmara', cidade: 'Asmara' },
    { nome: 'Fiat Tagliero', wiki: 'Edifício Fiat Tagliero', cidade: 'Asmara' },
  ],
  DJ: [
    { nome: 'Lago Assal', wiki: 'Lago Assal', cidade: 'Tadjourah' },
    { nome: 'Lago Abbé', wiki: 'Lago Abe', cidade: 'Dikhil' },
    { nome: 'Djibuti (cidade)', wiki: 'Djibuti (cidade)', cidade: 'Djibouti' },
    { nome: 'Floresta de Day', wiki: 'Parque Nacional Forêt du Day', cidade: 'Tadjourah' },
    { nome: 'Golfo de Tadjoura', wiki: 'Golfo de Tadjoura', cidade: 'Tadjourah' },
    { nome: 'Ardoukoba', wiki: 'Ardoukoba', cidade: 'Tadjourah' },
  ],
  SO: [
    { nome: 'Mogadíscio', wiki: 'Mogadíscio', cidade: 'Banaadir' },
    { nome: 'Hargeisa', wiki: 'Hargeisa', cidade: 'Somalilândia' },
    { nome: 'Laas Geel', wiki: 'Laas Geel', cidade: 'Somalilândia' },
    { nome: 'Berbera', wiki: 'Berbera', cidade: 'Somalilândia' },
    { nome: 'Praia de Liido', wiki: 'Mogadíscio', cidade: 'Mogadíscio' },
    { nome: 'Catedral de Mogadíscio', wiki: 'Catedral de Mogadíscio', cidade: 'Mogadíscio' },
  ],
  BI: [
    { nome: 'Bujumbura', wiki: 'Bujumbura', cidade: 'Bujumbura' },
    { nome: 'Lago Tanganica', wiki: 'Lago Tanganica', cidade: 'Bujumbura' },
    { nome: 'Parque Nacional Kibira', wiki: 'Parque Nacional Kibira', cidade: 'Kayanza' },
    { nome: 'Parque Nacional Rusizi', wiki: 'Parque Nacional Rusizi', cidade: 'Bujumbura Rural' },
    { nome: 'Cataratas Karera', wiki: 'Cataratas Karera', cidade: 'Rutana' },
    { nome: 'Fonte do Nilo no sul', wiki: 'Rio Nilo', cidade: 'Rutovu' },
    { nome: 'Gitega', wiki: 'Gitega', cidade: 'Gitega' },
  ],
  LR: [
    { nome: 'Monróvia', wiki: 'Monróvia', cidade: 'Montserrado' },
    { nome: 'Parque Nacional Sapo', wiki: 'Parque Nacional Sapo', cidade: 'Sinoe' },
    { nome: 'Praia de Robertsport', wiki: 'Robertsport', cidade: 'Grand Cape Mount' },
    { nome: 'Providence Island', wiki: 'Providence Island (Libéria)', cidade: 'Monróvia' },
    { nome: 'Floresta Wonegizi', wiki: 'Reserva Florestal de Wonegizi', cidade: 'Lofa' },
    { nome: 'Lago Piso', wiki: 'Lago Piso', cidade: 'Grand Cape Mount' },
  ],
  SL: [
    { nome: 'Freetown', wiki: 'Freetown', cidade: 'Área Ocidental' },
    { nome: 'Cotton Tree', wiki: 'Cotton Tree (Serra Leoa)', cidade: 'Freetown' },
    { nome: 'Bunce Island', wiki: 'Ilha de Bunce', cidade: 'Porto Lokó' },
    { nome: 'Parque Nacional Outamba-Kilimi', wiki: 'Parque Nacional Outamba-Kilimi', cidade: 'Bombali' },
    { nome: 'Tiwai Island Wildlife Sanctuary', wiki: 'Ilha Tiwai', cidade: 'Pujehun' },
    { nome: 'Praias da Península de Freetown', wiki: 'Península da Serra Leoa', cidade: 'Freetown' },
    { nome: 'Mount Bintumani', wiki: 'Loma Mansa', cidade: 'Koinadugu' },
  ],
  GN: [
    { nome: 'Conacri', wiki: 'Conacri', cidade: 'Conacri' },
    { nome: 'Fouta Djallon', wiki: 'Fouta Djallon', cidade: 'Labé' },
    { nome: 'Reserva Natural Estrita do Monte Nimba', wiki: 'Reserva Natural do Monte Nimba', cidade: 'Lola' },
    { nome: 'Cataratas Kambadaga', wiki: 'Cataratas Kambadaga', cidade: 'Fouta Djallon' },
    { nome: 'Ilhas de Los', wiki: 'Ilhas dos Idolos', cidade: 'Conacri' },
    { nome: 'Mesquita Faisal', wiki: 'Conacri', cidade: 'Conacri' },
  ],
  GW: [
    { nome: 'Arquipélago dos Bijagós', wiki: 'Bijagós', cidade: 'Bolama' },
    { nome: 'Bissau', wiki: 'Bissau', cidade: 'Bissau' },
    { nome: 'Parque Nacional Marinho João Vieira-Poilão', wiki: 'Parque Nacional Marinho João Vieira-Poilão', cidade: 'Bijagós' },
    { nome: 'Parque Nacional de Cantanhez', wiki: 'Parque Nacional de Cantanhez', cidade: 'Tombali' },
    { nome: 'Bolama', wiki: 'Bolama', cidade: 'Bolama' },
    { nome: 'Praças coloniais de Bissau', wiki: 'Bissau', cidade: 'Bissau' },
  ],
  ST: [
    { nome: 'Pico Cão Grande', wiki: 'Pico Cão Grande', cidade: 'São Tomé' },
    { nome: 'Ilhéu das Rolas', wiki: 'Ilhéu das Rolas', cidade: 'Caué' },
    { nome: 'Parque Natural Obô', wiki: 'Parque Natural Obô', cidade: 'São Tomé' },
    { nome: 'Praia das Sete Ondas', wiki: 'Praia das Sete Ondas', cidade: 'Caué' },
    { nome: 'Roça Agostinho Neto', wiki: 'Roça Agostinho Neto', cidade: 'Lobata' },
    { nome: 'Pico de São Tomé', wiki: 'Pico de São Tomé', cidade: 'São Tomé' },
    { nome: 'Cidade de São Tomé', wiki: 'São Tomé (cidade)', cidade: 'São Tomé' },
  ],
  KM: [
    { nome: 'Moroni', wiki: 'Moroni (Comores)', cidade: 'Grande Comore' },
    { nome: 'Karthala', wiki: 'Karthala', cidade: 'Grande Comore' },
    { nome: 'Anjouan', wiki: 'Anjouan', cidade: 'Anjouan' },
    { nome: 'Mohéli', wiki: 'Mohéli', cidade: 'Mohéli' },
    { nome: 'Parque Marinho de Mohéli', wiki: 'Parque Nacional Marinho de Mohéli', cidade: 'Mohéli' },
    { nome: 'Mutsamudu', wiki: 'Mutsamudu', cidade: 'Anjouan' },
  ],
  KI: [
    { nome: 'Tarawa', wiki: 'Tarawa', cidade: 'Sul de Tarawa' },
    { nome: 'Atol de Kiritimati', wiki: 'Quirítimati', cidade: 'Ilhas da Linha' },
    { nome: 'Área Protegida das Ilhas Phoenix', wiki: 'Área Protegida das Ilhas Fênix', cidade: 'Ilhas Fênix' },
    { nome: 'Banaba', wiki: 'Banaba', cidade: 'Rabi' },
    { nome: 'Bairiki', wiki: 'Bairiki', cidade: 'Tarawa' },
    { nome: 'Memorial de Betio', wiki: 'Batalha de Tarawa', cidade: 'Betio' },
    { nome: 'Ilhas Gilbert', wiki: 'Ilhas Gilbert', cidade: 'Tarawa' },
  ],
  MH: [
    { nome: 'Atol de Bikini', wiki: 'Atol de Bikini', cidade: 'Bikini' },
    { nome: 'Majuro', wiki: 'Majuro', cidade: 'Majuro' },
    { nome: 'Atol de Kwajalein', wiki: 'Atol de Kwajalein', cidade: 'Kwajalein' },
    { nome: 'Arno Atoll', wiki: 'Arno', cidade: 'Arno' },
    { nome: 'Mili Atoll', wiki: 'Mili (atol)', cidade: 'Mili' },
    { nome: 'Atol de Enewetak', wiki: 'Enewetak', cidade: 'Enewetak' },
    { nome: 'Ilhas Marshall (cadeias Ratak e Ralik)', wiki: 'Ilhas Marshall', cidade: 'Majuro' },
  ],
  FM: [
    { nome: 'Nan Madol', wiki: 'Nan Madol', cidade: 'Pohnpei' },
    { nome: 'Palikir', wiki: 'Palikir', cidade: 'Pohnpei' },
    { nome: 'Chuuk Lagoon', wiki: 'Lagoa Chuuk', cidade: 'Chuuk' },
    { nome: 'Yap', wiki: 'Yap', cidade: 'Yap' },
    { nome: 'Kosrae', wiki: 'Kosrae', cidade: 'Kosrae' },
    { nome: 'Pedras de Pedra de Yap', wiki: 'Rai (moeda)', cidade: 'Yap' },
  ],
  NR: [
    { nome: 'Yaren', wiki: 'Yaren', cidade: 'Yaren' },
    { nome: 'Buada Lagoon', wiki: 'Buada Lagoon', cidade: 'Buada' },
    { nome: 'Comando Ridge', wiki: 'Comando Ridge', cidade: 'Nauru' },
    { nome: 'Anibare Bay', wiki: 'Anibare', cidade: 'Anibare' },
    { nome: 'Moqua Caves', wiki: 'Moqua Caves', cidade: 'Anabar' },
    { nome: 'Aeroporto Internacional de Nauru', wiki: 'Aeroporto Internacional de Nauru', cidade: 'Yaren' },
    { nome: 'Capital de Nauru (sem capital oficial)', wiki: 'Nauru', cidade: 'Yaren' },
  ],
  TV: [
    { nome: 'Funafuti', wiki: 'Funafuti', cidade: 'Funafuti' },
    { nome: 'Área de Conservação de Funafuti', wiki: 'Área de Conservação de Funafuti', cidade: 'Funafuti' },
    { nome: 'Nanumea', wiki: 'Nanumea', cidade: 'Nanumea' },
    { nome: 'Nukufetau', wiki: 'Nukufetau', cidade: 'Nukufetau' },
    { nome: 'Vaiaku', wiki: 'Vaiaku', cidade: 'Funafuti' },
    { nome: 'Niutao', wiki: 'Niutao', cidade: 'Niutao' },
    { nome: 'Nui', wiki: 'Nui (Tuvalu)', cidade: 'Nui' },
  ],
  KN: [
    { nome: 'Brimstone Hill Fortress', wiki: 'Brimstone Hill Fortress', cidade: 'São Cristóvão' },
    { nome: 'Basseterre', wiki: 'Basseterre', cidade: 'São Cristóvão' },
    { nome: 'Charlestown (Nevis)', wiki: 'Charlestown (Nevis)', cidade: 'Nevis' },
    { nome: 'Mount Liamuiga', wiki: 'Monte Liamuiga', cidade: 'São Cristóvão' },
    { nome: 'Nevis Peak', wiki: 'Pico de Nevis', cidade: 'Nevis' },
    { nome: 'St. Kitts Scenic Railway', wiki: 'St. Kitts Scenic Railway', cidade: 'São Cristóvão' },
    { nome: 'Romney Manor', wiki: 'Romney Manor', cidade: 'São Cristóvão' },
  ],
  VC: [
    { nome: 'Tobago Cays', wiki: 'Tobago Cays', cidade: 'Grenadinas' },
    { nome: 'Kingstown', wiki: 'Kingstown (São Vicente)', cidade: 'São Vicente' },
    { nome: 'La Soufrière', wiki: 'La Soufrière (São Vicente)', cidade: 'São Vicente' },
    { nome: 'Bequia', wiki: 'Bequia', cidade: 'Grenadinas' },
    { nome: 'Mustique', wiki: 'Mustique', cidade: 'Grenadinas' },
    { nome: 'Union Island', wiki: 'Union Island', cidade: 'Grenadinas' },
    { nome: 'Jardim Botânico de Kingstown', wiki: 'Jardim Botânico de Kingstown', cidade: 'Kingstown' },
  ],
};
