// Override de título da Wikipédia para CIDADES. A lista d.cidades é string[] usada em
// 6 telas, então não dá pra reestruturar — este mapa resolve ambiguidade/sem-foto sem
// mudar o nome exibido. Ex.: "Lagos" (desambiguação que cai em Lagos/Nigéria) →
// "Lagos (Portugal)". Chave: `${code}:${cidade}`. Serve a FOTO (server) e a HISTÓRIA
// do modal (client). Curadoria manual — adicionar conforme a varredura por país.
export const CIDADE_WIKI = {
  'AD:Andorra-a-Velha (Andorra la Vella)': 'Andorra-a-Velha',
  'BD:Daca (Dhaka)': 'Daca',
  'BG:Varna': 'Varna (Bulgária)',
  'BN:Bandar Seri Begawan (capital)': 'Bandar Seri Begawan',
  'BN:Bangar (Temburong)': 'Temburong',
  'BN:Kampong Ayer (vila sobre as águas)': 'Kampong Ayer (Brunei)',
  'BN:Tutong': 'Tutong (distrito)',
  'BS:Freeport (Grand Bahama)': 'Grand Bahama',
  'BS:Nassau': 'Nassau (Bahamas)',
  'BY:Brest': 'Brest (Belarus)',
  'BZ:San Pedro (Ambergris Caye)': 'Ambergris Caye',
  'CK:Avarua (Rarotonga)': 'Avarua',
  'CK:Ilha Aitutaki': 'Aitutaki',
  'CM:Limbe': 'Limbe (Camarões)',
  'CO:Cartagena': 'Cartagena (Colômbia)',
  'CR:La Fortuna (vulcão Arenal)': 'Parque Nacional Vulcão Arenal',
  'CR:San José': 'San José (Costa Rica)',
  'CV:Boa Vista (Sal Rei)': 'Boa Vista (Cabo Verde)',
  'CV:Mindelo (São Vicente)': 'Mindelo (Cabo Verde)',
  'CV:Praia (Santiago)': 'Praia (Cabo Verde)',
  'DO:Samaná': 'Samaná (cidade)',
  'DZ:Argel (Alger)': 'Argel',
  'DZ:Constantine': 'Constantine (Argélia)',
  'EC:Cuenca': 'Cuenca (Equador)',
  'EG:Assuão (Aswan)': 'Assuão',
  'ET:Axum (Aksum)': 'Império de Axum',
  'FI:Rovaniemi (Lapônia)': 'Lapónia (Finlândia)',
  'FJ:Ilha Denarau': 'Ilha Robinson Crusoe (Fiji)',
  'GH:Cape Coast (Castelo)': 'Cape Coast',
  'GT:Flores (Tikal)': 'Flores (Guatemala)',
  'GY:Georgetown': 'Georgetown (Guiana)',
  'GY:Kaieteur (parque)': 'Cataratas de Kaieteur',
  'HK:Hong Kong (Ilha)': 'Ilha de Hong Kong',
  'HN:Copán (ruínas)': 'Copán (Honduras)',
  'HN:Roatán (Ilhas da Baía)': 'Ilhas da Baía',
  'HT:Porto Príncipe (Port-au-Prince)': 'Porto Príncipe',
  'JO:Petra (Wadi Musa)': 'Petra',
  'KG:Lago Issyk-Kul (Cholpon-Ata / Karakol)': 'Lago Issyk-Kul',
  'KW:Hawalli': 'Hawalli (província)',
  'KZ:Astana (Nur-Sultan)': 'Astana',
  'LB:Biblos (Jbeil)': 'Biblos',
  'LC:Soufrière (Pitons)': 'Pitons',
  'MC:Fontvieille': 'Fontvieille (Mônaco)',
  'MC:Mônaco-Ville (a Rocha)': 'Monaco-Ville',
  'MD:Cricova (adegas)': 'Cricova',
  'MD:Orhei (Orheiul Vechi)': 'Orhei',
  'MD:Tiraspol (Transnístria)': 'Transnístria',
  'MG:Morondava (Avenida dos Baobás)': 'Avenida dos Baobás',
  'MG:Toamasina (Tamatave)': 'Toamasina',
  'MK:Mavrovo': 'Mavrovo e Rostusa',
  'MM:Lago Inle (Nyaung Shwe)': 'Lago Inle',
  'MM:Yangon (Rangum)': 'Rangum',
  'MO:Macau (Península)': 'Península de Macau',
  'MZ:Tofo (Inhambane)': 'Inhambane',
  'NA:Sossusvlei (Sesriem)': 'Sossusvlei',
  'NC:Ilha Lifou': 'Lifou',
  'NI:León': 'León (Nicarágua)',
  'OM:Mascate (Muscat)': 'Mascate',
  'PA:Bocas del Toro': 'Bocas del Toro (província)',
  'PF:Papeete (Tahiti)': 'Papeete',
  'PR:Rincón': 'Rincón (Porto Rico)',
  'PR:San Juan': 'San Juan (Porto Rico)',
  'PT:Lagos': 'Lagos (Portugal)',
  'PW:Melekeok (Ngerulmud)': 'Ngerulmud',
  'RW:Parque Nacional dos Vulcões (gorilas)': 'Parque Nacional dos Vulcões',
  'SA:Jidá (Jeddah)': 'Jeddah Tower',
  'SB:Honiara (Guadalcanal)': 'Guadalcanal (Ilhas Salomão)',
  'SB:Ilha Munda': 'Santa Helena (ilha)',
  'SC:Beau Vallon': 'Beau Vallon (Seicheles)',
  'SC:La Digue (Anse Source d\'Argent)': 'La Digue',
  'SC:Praslin (Anse Lazio)': 'Praslin',
  'SC:Victoria (Mahé)': 'Victoria, Seychelles',
  'SN:Saint-Louis': 'Saint-Louis (Senegal)',
  'TJ:Murghab (Pamir Highway)': 'Estrada do Pamir',
  'TM:Asgabate (Ashgabat)': 'Asgabate',
  'TM:Cratera de Darvaza (\'Portão do Inferno\')': 'Cratera de Darvaza',
  'TM:Mary (próxima às ruínas de Merv)': 'Mary (Turcomenistão)',
  'TO:Ilha Ha\'apai': 'Ha\'apai',
  'TO:Vava\'u (Neiafu)': 'Vava\'u',
  'TT:Chaguaramas': 'Chaguaramas, Trinidad and Tobago',
  'TT:Crown Point (Tobago)': 'Crown Point, Tobago',
  'TT:Porto da Espanha (Port of Spain)': 'Port of Spain',
  'UG:Bwindi (gorilas)': 'Parque Nacional Impenetrável de Bwindi',
  'UG:Jinja': 'Jinja (Uganda)',
  'VE:Mérida': 'Mérida (Venezuela)',
  'VU:Ilha Espiritu Santo': 'Espírito Santo (ilha)',
  'VU:Ilha Tanna (vulcao Yasur)': 'Monte Yasur',
  'WS:Ilha Savai\'i': 'Savai\'i',
  'WS:Ilha Upolu': 'Upolu',
  'XK:Peja (Peć)': 'Peja (Kosovo)',
  'ZM:Livingstone (Cataratas Vitória)': 'Livingstone (Zâmbia)',
  'ZM:Parque Nacional South Luangwa': 'Parque Nacional do Luangwa do Sul',
  'ZW:Victoria Falls (cidade)': 'Victoria Falls',
};

export function cidadeWiki(code, cidade) {
  return CIDADE_WIKI[`${code}:${cidade}`] || cidade;
}
