// REGISTRO DE PROVEDORES (OMEGA V4 §27-28) — fonte única usada pela página /fontes
// e por docs/PROVIDER-MATRIX.md. Estado verificado em 2026-10-09 (requisições reais
// feitas a partir deste ambiente; termos lidos nas páginas oficiais).
// estado: UNRESEARCHED | RESEARCHED | CONTRACT_REQUIRED | KEY_REQUIRED | MOCK_ONLY |
//         ADAPTER_READY | SANDBOX_VERIFIED | LIVE_VERIFIED | DEGRADED | DISABLED
export const VERIFICADO_EM = '2026-10-09';

export const PROVEDORES = [
  // ---- mapas, geo, rotas ----
  { id: 'openfreemap', nome: 'OpenFreeMap (tiles OSM)', dominio: 'Mapas', uso: 'Mapa interativo (Explorar, destino, roteiro)', onde: 'browser', auth: 'sem chave', estado: 'LIVE_VERIFIED', frescor: 'LIVE', atribuicao: '© OpenMapTiles · dados © OpenStreetMap (automática no mapa)', limite: 'Sem limite declarado; serviço doado, “as is”', custo: 'Grátis (doações)', fallback: 'Lista textual equivalente; aviso “mapa indisponível”', termos: 'https://openfreemap.org/tos/', nota: 'Uso comercial permitido com atribuição.' },
  { id: 'fossgis-osrm', nome: 'OSRM · FOSSGIS (routing.openstreetmap.de)', dominio: 'Rotas', uso: 'Rota real a pé/bike/carro no roteiro e no Modo Viagem', onde: 'browser', auth: 'sem chave', estado: 'LIVE_VERIFIED', frescor: 'LIVE', atribuicao: 'OSRM · FOSSGIS · © OpenStreetMap', limite: '≤ 1 req/s, uso leve (respeitado por fila no cliente)', custo: 'Grátis', fallback: 'Tempo estimado por distância, rotulado ESTIMATIVA', termos: 'https://routing.openstreetmap.de/about.html', nota: 'Escala de produção exige servidor OSRM/Valhalla próprio ou provedor pago → bloqueio de escala.' },
  { id: 'transit', nome: 'Transporte público em tempo real (GTFS-RT)', dominio: 'Rotas', uso: 'Horários reais de metrô/ônibus/trem', onde: '—', auth: '—', estado: 'RESEARCHED', frescor: 'UNAVAILABLE', atribuicao: '—', limite: '—', custo: 'Varia por cidade/agregador', fallback: 'Tempo de transporte ESTIMADO, rotulado', termos: '—', nota: 'Requer agregador (ex.: Google Routes, Navitia, Transitland) com contrato.' },
  { id: 'wikipedia-geo', nome: 'Wikipedia + Wikidata (coordenadas)', dominio: 'Geo', uso: 'Coordenadas canônicas de 2.755 atrações e 1.063 cidades', onde: 'build/servidor', auth: 'sem chave (User-Agent identificado)', estado: 'LIVE_VERIFIED', frescor: 'RECENT', atribuicao: 'Wikipedia / Wikidata (CC BY-SA / CC0)', limite: 'Boas práticas de API (lotes de 50)', custo: 'Grátis', fallback: 'Sem pino (melhor que pino errado)', termos: 'https://foundation.wikimedia.org/wiki/Policy:Terms_of_Use', nota: 'Gerado por scripts/geo/geocodificar.mjs em 2026-10-09.' },
  // ---- fotos e conteúdo ----
  { id: 'wikimedia-commons', nome: 'Wikimedia Commons', dominio: 'Fotos', uso: 'Fotos de países, cidades e atrações com autor e licença', onde: 'servidor (resolução) + browser (thumb)', auth: 'sem chave', estado: 'LIVE_VERIFIED', frescor: 'RECENT', atribuicao: 'Autor + licença por foto (botão ©)', limite: 'Somente larguras padrão de thumbnail; originais têm limite de taxa', custo: 'Grátis', fallback: 'Foto ilustrativa ROTULADA ou placeholder honesto', termos: 'https://commons.wikimedia.org/wiki/Commons:Reusing_content_outside_Wikimedia', nota: 'Corrigido o uso de larguras não padrão (400/429) achado no QA do Lote 0.' },
  { id: 'wikipedia-texto', nome: 'Wikipedia (resumos)', dominio: 'Conteúdo', uso: '“Sobre o país” e história dos lugares', onde: 'servidor + browser', auth: 'sem chave', estado: 'LIVE_VERIFIED', frescor: 'RECENT', atribuicao: 'Link “Ler na Wikipédia”', limite: 'Boas práticas', custo: 'Grátis', fallback: 'Contexto editorial do país', termos: 'https://foundation.wikimedia.org/wiki/Policy:Terms_of_Use', nota: '' },
  { id: 'openverse', nome: 'Openverse', dominio: 'Fotos', uso: 'Fallback de foto com licença CC comercial', onde: 'servidor', auth: 'sem chave', estado: 'LIVE_VERIFIED', frescor: 'RECENT', atribuicao: 'Autor + licença + link', limite: 'Anônimo com limite baixo', custo: 'Grátis', fallback: 'Próximo da cascata', termos: 'https://openverse.org/terms', nota: '' },
  { id: 'flagcdn', nome: 'flagcdn', dominio: 'Ícones', uso: 'Bandeiras', onde: 'browser', auth: 'sem chave', estado: 'LIVE_VERIFIED', frescor: 'LIVE', atribuicao: 'Domínio público', limite: '—', custo: 'Grátis', fallback: 'Sem bandeira', termos: 'https://flagcdn.com', nota: '' },
  // ---- dinheiro e clima ----
  { id: 'frankfurter', nome: 'Frankfurter (taxas do BCE)', dominio: 'Câmbio', uso: 'Conversão de despesas', onde: 'browser', auth: 'sem chave', estado: 'LIVE_VERIFIED', frescor: 'RECENT', atribuicao: 'BCE via frankfurter.dev', limite: '—', custo: 'Grátis', fallback: 'open.er-api; senão despesa salva sem conversão (avisado)', termos: 'https://frankfurter.dev', nota: 'Taxa de referência diária (dias úteis) — não é a taxa do cartão.' },
  { id: 'open-er-api', nome: 'ExchangeRate-API (open.er-api.com)', dominio: 'Câmbio', uso: 'Câmbio USD→BRL dos preços de referência e moedas fora do BCE', onde: 'browser', auth: 'sem chave', estado: 'LIVE_VERIFIED', frescor: 'RECENT', atribuicao: 'ExchangeRate-API', limite: 'Atualização diária; uso razoável', custo: 'Grátis (plano aberto)', fallback: 'Valor fixo de referência rotulado ESTIMATIVA', termos: 'https://www.exchangerate-api.com/docs/free', nota: '' },
  { id: 'open-meteo', nome: 'Open-Meteo', dominio: 'Clima', uso: 'Previsão do dia, fuso do destino, Plano B de chuva', onde: 'browser', auth: 'sem chave', estado: 'CONTRACT_REQUIRED', frescor: 'LIVE', atribuicao: 'Open-Meteo.com (CC BY 4.0)', limite: '10.000 chamadas/dia (gratuito)', custo: 'Gratuito só para uso NÃO comercial; API comercial paga', fallback: 'Sem previsão (aviso)', termos: 'https://open-meteo.com/en/terms', nota: 'Funciona hoje (verificado); antes de lançar com receita, contratar a API comercial — bloqueio externo.' },
  // ---- viagem / comércio ----
  { id: 'voos', nome: 'Busca de voos ao vivo (Duffel / Travelpayouts / Amadeus)', dominio: 'Voos', uso: 'Ofertas reais com preço total e bagagem', onde: 'servidor', auth: 'chave de API', estado: 'KEY_REQUIRED', frescor: 'UNAVAILABLE', atribuicao: '—', limite: '—', custo: 'Conforme contrato', fallback: 'CENÁRIOS ESTIMADOS por distância (sem nomes de companhias) + links para buscadores', termos: 'https://duffel.com/legal', nota: 'Sem chave/contrato → nenhuma oferta é exibida como real.' },
  { id: 'hoteis', nome: 'Hospedagem (Expedia Rapid / Booking Affiliate)', dominio: 'Hotéis', uso: 'Preço total com taxas e disponibilidade', onde: 'servidor', auth: 'contrato de parceiro', estado: 'CONTRACT_REQUIRED', frescor: 'UNAVAILABLE', atribuicao: '—', limite: '—', custo: 'Comissão', fallback: 'DEEPLINK para busca no parceiro (você sai do site, avisado)', termos: '—', nota: '' },
  { id: 'experiencias', nome: 'Experiências (Viator / GetYourGuide / Civitatis / Klook)', dominio: 'Experiências', uso: 'Ingressos com horário e disponibilidade', onde: 'servidor', auth: 'chave de parceiro', estado: 'KEY_REQUIRED', frescor: 'UNAVAILABLE', atribuicao: '—', limite: '—', custo: 'Comissão', fallback: 'Preço de referência HISTÓRICO + DEEPLINK', termos: '—', nota: '' },
  { id: 'afiliados', nome: 'Tags de afiliado (Booking, Viator, GYG, Klook, Civitatis, Travelpayouts, Wise, SafetyWing)', dominio: 'Monetização', uso: 'Comissão em links de saída', onde: 'browser (links)', auth: 'IDs públicos por env', estado: 'ADAPTER_READY', frescor: '—', atribuicao: 'Aviso de saída + rel="sponsored"', limite: '—', custo: '—', fallback: 'Link sem tag (no-op seguro)', termos: '—', nota: 'Cadastro nos programas é do dono do produto. A comissão nunca entra no ranking (teste automatizado).' },
  { id: 'stripe', nome: 'Stripe', dominio: 'Pagamentos', uso: 'Assinaturas Premium/Pro', onde: 'servidor', auth: 'chave secreta + webhook', estado: 'ADAPTER_READY', frescor: '—', atribuicao: '—', limite: '—', custo: 'Taxa por transação', fallback: 'Plano grátis (no-op seguro)', termos: 'https://stripe.com/legal', nota: 'Webhook com assinatura, dedupe e ordem. Falta chave/preço do dono para SANDBOX_VERIFIED.' },
  { id: 'supabase', nome: 'Supabase', dominio: 'Conta e sync', uso: 'Login, assinaturas, sync de viagens', onde: 'browser + servidor', auth: 'anon key + service role', estado: 'ADAPTER_READY', frescor: '—', atribuicao: '—', limite: '—', custo: 'Plano Supabase', fallback: 'Tudo local no aparelho', termos: 'https://supabase.com/terms', nota: 'RLS testado em Postgres real (34 casos). Precisa aplicar as migrations no projeto do dono.' },
  { id: 'ia', nome: 'LLM (OpenAI-compatível)', dominio: 'IA', uso: 'Roteiro e oportunidades com IA', onde: 'servidor', auth: 'chave de API', estado: 'KEY_REQUIRED', frescor: '—', atribuicao: '—', limite: 'Cota diária por usuário', custo: 'Por token', fallback: 'Modo sem IA / chave do próprio usuário', termos: '—', nota: 'Só para usuário logado; IA não define visto nem preço.' },
  { id: 'vistos', nome: 'Regras de entrada (visto/saúde) oficiais', dominio: 'Documentos', uso: 'Visto por passaporte e país', onde: 'catálogo', auth: '—', estado: 'RESEARCHED', frescor: 'HISTORICAL', atribuicao: 'Compilação jun/2026', limite: '—', custo: 'APIs especializadas (ex.: Sherpa, Timatic) são pagas', fallback: '“Consultar consulado” quando não há regra', termos: '—', nota: 'Sempre com aviso de confirmar no órgão oficial.' },
];

export const ROTULO_ESTADO = {
  LIVE_VERIFIED: 'Ativo e verificado', SANDBOX_VERIFIED: 'Verificado em sandbox', ADAPTER_READY: 'Integração pronta, falta credencial',
  KEY_REQUIRED: 'Precisa de chave', CONTRACT_REQUIRED: 'Precisa de contrato', MOCK_ONLY: 'Somente simulação', RESEARCHED: 'Pesquisado',
  UNRESEARCHED: 'Não pesquisado', DEGRADED: 'Degradado', DISABLED: 'Desligado',
};
